=== stefaweb/XAMS-0.3.x/gui/include/dtd/help.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT maintainers (maintainer+)>
<!ELEMENT maintainer (name, email)>
<!ATTLIST information
    usertype CDATA "0"
    minusertype CDATA "0"
>
<!ELEMENT information (#PCDATA)>
<!ELEMENT head (#PCDATA)>
<!ELEMENT condition (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ATTLIST section
    usertype CDATA "0"
    minusertype CDATA "0"
>
<!ELEMENT section (head, condition?, description)>
<!ATTLIST lngspec
    name CDATA #REQUIRED
    iso CDATA #REQUIRED
    localname CDATA #REQUIRED
>
<!ELEMENT lngspec EMPTY>
<!ELEMENT skindir (#PCDATA)>
<!ATTLIST help
    title CDATA #REQUIRED
    xams-release CDATA #REQUIRED
    file-release CDATA #REQUIRED
    file-revision CDATA #REQUIRED
    date CDATA #REQUIRED
>
<!ELEMENT help (lngspec, skindir, maintainers, information?, section+)>

=== stefaweb/XAMS-0.3.x/gui/i18n/german/help/user_addressbook.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE help SYSTEM "../../../include/dtd/help.dtd">
<help title="Benutzer-Adressbuch Verwaltung" xams-release="0.0.9" file-release="0.0.9" file-revision="1" date="2002-11-31">
    <lngspec name="german" iso="de" localname="deutsch"/>
    <skindir>{{skindir}}</skindir>
    <maintainers>
        <maintainer>
            <name>XAMS Core-Team</name>
            <email>info@xams.org</email>
        </maintainer>
    </maintainers>
    <information>
        Das XAMS Adressbuch bietet die Möglichkeit für Sites, Benutzer,
        Aliase, Wiederverkäufer und Endkunden ein Adressbuch anzulegen.
        Die Felder für dieses Adressbuch (wie z.B. Name, Straße, etc.)
        können und müssen hierfür selbst angelegt werden. Dies hat
        den Vorteil, dass jedes System genau die Felder für die Bereiche
        zur Verfügung stellt, welche der Administrator für sinnvoll
        erachtet.
    </information>
    <section>
        <head>Feldname</head>
        <description>
            Tragen Sie hier Feldnamen ein, die in Ihrem Benutzer-Adressbuch zur
            Verfügung stehen sollen.
        </description>
    </section>
    <section>
        <head>LDAP</head>
        <description>
            Mit LDAP (Lightweight Directory Access Protocol) bietet XAMS die
            Möglichkeit, bestimmte Adressbuch-Felder in eine solche Datenbank
            unter dem angegebenen Feldnamen zu exportieren. Diese LDAP
            Datenbank kann dann von verschiedenen Applikationen als globales
            Adressbuch angebunden werden.
        </description>
    </section>
    <section>
        <head>ACL Wiederverkäufer</head>
        <description>
            Die ACL Wiederverkäufer (Access Control List) dient der Kontrolle,
            welchen Zugriff der Wiederverkäufer auf dieses Feld hat. Mit dem
            Wert "Nichts" können ihm sämtliche Rechte entzogen werden (weder
            Lesen noch schreiben) die beiden anderen Zustände "Lesen" bzw.
            "Lesen+Schreiben" legen Fest, ob er die Werte dieser Felder lesen
            oder gar verändern kann.
        </description>
    </section>
    <section>
        <head>ACL Endkunde</head>
        <description>
            Analog zu den "ACL Wiederverkäufer" können hier die Rechte für
            die Endkunden eingestellt werden.
        </description>
    </section>
    <section>
        <head>ACL Benutzer</head>
        <description>
            Analog zu den "ACL Wiederverkäufer" können hier die Rechte für
            die Benutzer selbst eingestellt werden.
        </description>
    </section>
    <section>
        <head>Feld verschieben</head>
        <description>
            Diese Funktion dient dazu, die Reihenfolge der Einträge zu ändern.
            Die Auswahlliste zeigt alle verfügbaren Feldnamen an; wählen Sie
            einen Eintrag aus, dann wird das aktuelle Feld nach der
            ausgewählten Position plaziert.
        </description>
    </section>
    <section>
        <head>Löschen</head>
        <description>
            Setzen Sie einen Haken hinter die Zeile und nach anschließender
            Aktualisierung werden die ausgewählten Felder gelöscht.
            ACHTUNG: Die Daten sämtlicher Benutzer, die in den Feldern stehen,
            werden ebenfalls gelöscht!
        </description>
    </section>
</help>

=== stefaweb/XAMS-0.3.x/gui/i18n/german/help/customer_reseller.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE help SYSTEM "../../../include/dtd/help.dtd">
<help title="Wiederverkäufer-Zuordnung" xams-release="0.0.9" file-release="0.0.9" file-revision="1" date="2002-11-31">
    <lngspec name="german" iso="de" localname="deutsch"/>
    <skindir>{{skindir}}</skindir>
    <maintainers>
        <maintainer>
            <name>XAMS Core-Team</name>
            <email>info@xams.org</email>
        </maintainer>
    </maintainers>
    <information>
        Jeder Endkunde muss einem bestimmten Wiederverkäufer zugeordnet werden,
        damit XAMS die Kontingente des Wiederverkäufer auf diesen Endkunden
        abbilden kann, bzw. die Kontingente des Wiederverkäufer, um den
        Verbrauch des Endkunden bzw. dessen Sites, dezimiert werden.
    </information>
    <section>
        <head>Wiederverkäufer</head>
        <description>
            Hier muss der Wiederverkäufer ausgewählt werden, zu dem der
            Endkunde gehören soll.
        </description>
    </section>
</help>

=== stefaweb/XAMS-0.3.x/gui/i18n/french/help/reseller.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE help SYSTEM "../../../include/dtd/help.dtd">
<help title="Administration des revendeurs" xams-release="0.0.19" file-release="0.0.9" file-revision="1" date="2008-12-03">
    <lngspec name="french" iso="fr" localname="french"/>
    <skindir>{{skindir}}</skindir>
    <maintainers>
        <maintainer>
            <name>ACTION-WEB</name>
            <email>xams@actionweb.fr</email>
        </maintainer>
    </maintainers>
    <information>
        Un Administrateur attribue des sites à un Revendeur. Ces sites peuvent ensuite être administré
        par ce revendeur. En fonction des limitations définies par l'administrateur, le revendeur peut 
        définir les clients qui auront accès à ces sites et les gérer.
        
        Pa rapport à l'administrateur qui peut tout faire, le revendeur n'a pas accès aux préférences
        du système, ni aux Carnets d'adresse et il ne peut aussi pas analyser la base de données XAMS. 
        Il ne peut aussi avoir accès qu'a ses propres cients.
    </information>
    <section>
        <head>Nom du revendeur</head>
        <description>
            C'est nom du revendeur tel qu'il apparait dans la gestion des logs. A la connexion, ce nom 
            doit être précédé par "res_" pour que le système XAMS sache à quelle type d'utilisateur il a affaire.
        </description>
    </section>
    <section>
        <head>Mot de passe du revendeur</head>
        <description>
            Utilisé en même temps que le nom du revendeur, le mot de passe est demandé à la connexion 
            pour pouvoir accèder à l'interface d'administration du système XAMS.
        </description>
    </section>
    <section>
        <head>Nbr. maximum de clients</head>
        <description>
            Cette valeur permet de définir combien de clients peut créer le revendeur.
        </description>
    </section>
    <section>
        <head>Nbr. maximum de sites</head>
        <description>
            Cette valeur permet de définir combien de sites peut créer le revendeur.
        </description>
    </section>
    <section>
        <head>Nbr. maximum de domaines</head>
        <description>
            Cette valeur permet de définir combien de domaines peut créer le revendeur.
        </description>
    </section>
    <section>
        <head>Nbr. maximum d'utilisateurs</head>
        <description>
            Cette valeur permet de définir le nombre maximum de client qui peuvent être
            défini pour un même site.
            
            Exemple : un revendeur a une limite de 20 utilisateurs. Il peut donc attribuer une limite
            pour un premier site de 5 utilisateurs et 15 pour un second site. 
            
            Le total des utilisateurs attribués ne pouvant excéder le total autorisé. Cette valeur
            n'affecte pas le total général des utilisateurs qui ne sont pas sous sa reponsabilité.
        </description>
    </section>
    <section>
        <head>Nbr. maximum d'alias</head>
        <description>
            Cette valeur permet de définir combien d'alias peut créer le revendeur.
        </description>
    </section>
    <section>
        <head>Quota maximum</head>
        <description>
            Cette valeur permet de définir le quota maximum général pour l'ensemble des sites
            que peut créer le revendeur.
        </description>
    </section>
    <section>
        <head>Quota maximum pour les sites</head>
        <description>
            Cette valeur permet de définir le quota maximum qu'un revendeur peut attribuer
            à un site unique.
        </description>
    </section>
    <section>
        <head>Quota maximum pour les utilisateurs</head>
        <description>
            Cette valeur permet de définir le quota maximum qu'un revendeur peut attribuer
            à un client unique. Il ne peut bien sur pas excéder le quota général pour le site
            auquel appartient l'utilisateur.
        </description>
    </section>
    <section>
        <head>Anti-Virus</head>
        <description>
            Si cette option est activée, il est possible de définir si le revendeur peut activer 
            l'Anti-Virus pour les sites des utilisateurs dont il a la responsabilité.
        </description>
    </section>
    <section>
        <head>Anti-SPAM</head>
        <description>
            Si cette option est activée, il est possible de définir si le revendeur peut activer 
            l'Anti-SPAM pour les sites des utilisateurs dont il a la responsabilité.
        </description>
    </section>
    <section>
        <head>Réglage des scores de Spam</head>
        <description>
			Ces deux options permettent de définir le niveau de déclenchement des filtres anti-spam. 
			Le "Score de base" défini le niveau à partir duquel un message pourra être considéré comme un SPAM. 
			A ce niveau, le message sera mis en quarantaine si le système anti-spam utilise le logiciel Mailscanner. 
			Le second niveau "Score limite", défini le niveau à partir duquel le message sera considéré comme un SPAM 
			devant être directement supprimé sans mise en quarantaine ni avertissement. Son score étant considéré
			comme suffisamment élevé pour qu'il n'y ait aucun risque de faux positif.
        </description>
    </section>    
    <section>
        <head>Sites (sélection multiple)</head>
        <description>
            Avec cette option, un administrateur peut atribuer un ou plusieurs site à un revendeur. Le
            revendeur peut ensuite attriber ses sites à un plusieurs clients ou les administrer lui même
            directement.
        </description>
    </section>
    <section>
        <head>Compte vérouillé</head>
        <description>
            Cette option permet à l'administrateur de vérouiller le compte d'un revendeur l'empêchant 
            ainsi de se connecter au système.
        </description>
    </section>
</help>

=== stefaweb/XAMS-0.3.x/gui/i18n/english/help/templates.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE help SYSTEM "../../../include/dtd/help.dtd">
<help title="Template Overview" xams-release="0.0.9" file-release="0.0.9" file-revision="1" date="2002-11-29">
    <lngspec name="english" iso="en" localname="english"/>
    <skindir>{{skindir}}</skindir>
    <maintainers>
        <maintainer>
            <name>XAMS Core-Team</name>
            <email>info@xams.org</email>
        </maintainer>
    </maintainers>    
    <information>
        Templates are a very powerful feature of XAMS, they help Users
        adding new accounts with individually saved templates.
        Most email-addresses or Sites are created with a similar scheme.
        If you know that this will be the case, then you can create a template
        in advance to speed up the task of account-creation. It is important that
        every user (no matter if admin, reseller or customer) has his own template -
        using templates from other users is impossible.
    </information>
    <section>
        <head>Site Templates</head>
        <description>
            You can create templates for Sites here. Editing and deleting is also possible.
        </description>
    </section>
    <section>
        <head>User Templates</head>
        <description>
            You can create templates for Users here. Editing and deleting is also possible.
        </description>
    </section>
</help>

=== stefaweb/XAMS-0.3.x/gui/i18n/english/help/reseller.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE help SYSTEM "../../../include/dtd/help.dtd">
<help title="Reseller Management" xams-release="0.0.16" file-release="0.0.9" file-revision="1" date="2004-05-18">
    <lngspec name="english" iso="en" localname="english"/>
    <skindir>{{skindir}}</skindir>
    <maintainers>
        <maintainer>
            <name>XAMS Core-Team</name>
            <email>info@xams.org</email>
        </maintainer>
    </maintainers>
    <information>
        An Administrator assigns any desired sites definitely to
        one Reseller. These sites then can be just administrated by this special Reseller.
        Here, he has to keep to the limitations given by the Administrator. He may
        apply - according to the limits - any desired Customers and also manage
        them.
        In contrast to the Administrator, he cannot take up changes to the
        system settings, to the field-configuration in the addressbook and
        it is not possible for him to analyse the database.
        In addition to that he cannot gain access to the customers belonging
        to another Reseller of course.
    </information>
    <section>
        <head>Reseller Name</head>
        <description>
            This is the Name of the Reseller as it is e.g. shown
            in the Event-Log. At login this name has to be prefixed by
            "res_", so that XAMS knows wich kind of user it has to
            validate.
        </description>
    </section>
    <section>
        <head>Reseller Password</head>
        <description>
            In conjunction with the Name and this Password, the Reseller
            can login to the XAMS GUI.
        </description>
    </section>
    <section>
        <head>Max. Customers</head>
        <description>
            This value defines, how much Customers a Reseller can create.
        </description>
    </section>
    <section>
        <head>Max. Sites</head>
        <description>
            This value defines, how much Sites a Reseller can create.
        </description>
    </section>
    <section>
        <head>Max. Domains</head>
        <description>
            This value defines, how much Domains a Reseller can create.
        </description>
    </section>
    <section>
        <head>Max. Users</head>
        <description>
            This value defines, how high a reseller can set the User-Limit
            on Site-Level.
            Example: A Reseller has a limit of 20 Users, so he can set
            the User-Limit of one Site to 5 and of another Site to
            15. So, the sum of all User-Limits on Site-Level can not exceed
            this limit.
            This value does only affects the maximum amount of Reseller's
            Users indirect.
        </description>
    </section>
    <section>
        <head>Max. Aliases</head>
        <description>
            Analog zu den Benutzern kann hier darüber bestimmt werden, wie hoch
            das Alias-Limit aller Sites eines Wiederverkäufers sein darf.
        </description>
    </section>
    <section>
        <head>Max. Quota</head>
        <description>
            The "Max. Quota" defines the maximum site of all Site-Quotas
            (resp. the sum of them) of a reseller.
        </description>
    </section>
    <section>
        <head>Max. Site-Quota</head>
        <description>
            This value defines, how much Site-Quota a Reseller can
            assign to a Site.
        </description>
    </section>
    <section>
        <head>Max. User-Quota</head>
        <description>
            This value defines, how much User-Quota a Reseller can
            assign to a user. Thereby the Site-Level Quota can not
            be exceeded.
        </description>
    </section>
    <section>
        <head>Viruscheck</head>
        <description>
            Here can be determined if this Reseller can enable
            Viruschecking for his Sites resp. their users.
        </description>
    </section>
    <section>
        <head>Spamcheck</head>
        <description>
            Here can be determined if this Reseller can enable
            Spamchecking for his Sites resp. their users.
        </description>
    </section>
    <section>
        <head>Sites</head>
        <description>
            Here, an Administrator can assign one or several Sites
            to a specific Reseller. The Reseller can then assign
            these Sites to his Customers or administrate them by
            himself.
        </description>
    </section>
    <section>
        <head>Account locked</head>
        <description>
            Using this option, an Administrator can lock Resellers.
            Thereby he can't login the XAMS GUI anymore.
        </description>
    </section>
</help>

=== stefaweb/XAMS-0.3.x/gui/i18n/french/help/site.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE help SYSTEM "../../../include/dtd/help.dtd">
<help title="Administration du site" xams-release="0.0.19" file-release="0.0.9" file-revision="1" date="2008-12-03">
    <lngspec name="french" iso="fr" localname="french"/>
    <skindir>{{skindir}}</skindir>
    <maintainers>
        <maintainer>
            <name>ACTION-WEB</name>
            <email>xams@actionweb.fr</email>
        </maintainer>
    </maintainers>    
    <information>
        Un site est un ensemble qui peut regrouper un ou plusieurs domaines, des utilisateurs
        et même des alias. Cet ensemble permet à un utilisateur d'avoir plusieurs adresses de messagerie qui pointent
        sur une seule boîte aux lettre de messagerie (un compte POP3 ou IMAP). 
        
        Par exemple, il est possible de définir un site nommé "SOCIETE-MAXIMUM". Dans ce site, il est possible de 
        définir les domaines "maximum.com" ou "maximum.net".
        
        Chacun des comptes de messagerie de ce site peuvent n'avoir qu'un seul compte de messagerie et recevoir des
        messages sur plusieurs adresses de messagerie. Par exemple, si on créé un compte "andre" sur le site,
        celui-ci pourra recevoir des messages sur "andre@maximum.com" ou "andre@maximum.net".
        
        Autre avantage, l'utilisateur n'aura qu'un seul compte de messagerie pour se connecter au système qu'il utilise
        le protocole POP3, IMAP, SMTP, ou même pour se connecter à l'interface d'administration d'XAMS.
    </information>
    <section>
        <head>Revendeur</head>
        <description>
            Cette option permet d'attribuer le site à un revendeur.
        </description>
    </section>
    <section>
        <head>Nom du site</head>
        <description>
            Saisir ici le nom du site. Celui-ci sera visible pour l'administrateur global d'XAMS ou
            pour chacun des autres administrateurs. Les droits d'administration peuvent être donnés
            uniquement pour ce niveau, ou même, séparement par domaines, utilisateurs ou alias.
        </description>
    </section>
    <section>
        <head>Domaines</head>
        <description>
            Saisissez ici le ou les noms de domaine attachés à ce site. Un nom de domaine valide est
            par exemple xams.org.
        </description>
    </section>
    <section>
        <head>Quota maximum</head>
        <description>
            Cette valeur permet de définir le quota maximum général de la taille de des boîtes aux lettres 
            pour l'ensemble des utilisateurs de ce site. Si le quota maximum est atteint, il ne sera plus 
            possible d'ajouter des utilisateurs à ce site.
        </description>
    </section>
    <section>
        <head>Quota maximum (par utilisateur)</head>
        <description>
            Cette valeur permet de définir le quota maximum de la taille de la boîte aux lettres 
            pour un seul utilisateur. Si un message dépassant la taille maximum autorisé est réceptionné,
            celui-ci sera ignoré et un message d'erreur envoyé à l'expéditeur. Il est bien sûr possible
            d'affecter un quota plus petit à un des utilisateurs mais dans les limites maximum défnies ici.
        </description>
    </section>
    <section>
        <head>Nbr. maximum d'utilisateur</head>
        <description>
            Cette valeur permet de définir le nombre maximum d'utilisateur qui peuvent être
            défini pour ce site. Seul l'administrateur global peut changer cette valeur.
            Un administrateur de site ne pourra pas dépasser les limites définies ici.
        </description>
    </section>
    <section>
        <head>Nbr. maximum d'alias</head>
        <description>
            Cette valeur permet de définir combien d'alias maximum peuvent être créer. Un administrateur de 
            site ne pourra pas changer cette valeur.
        </description>
    </section>
    <section>
        <head>Type</head>
        <description>
            Cette option permet de configurer le type de boîte aux lettre que peut avoir un utilisateur.
            Si par exemple, seul le type POP3 est activé, il ne sera pas possible que l'utilisateur possède
            une boîte aux lettres au format IMAP pour ce site.
        </description>
    </section>
    <section>
        <head>Anti-Virus</head>
        <description>
            Si cette option est activée, il est possible de définir si on veut activer la fonction Anti-Virus
            sur les messages entrants ou sortants. Il est possible de changer cette option par défaut aux niveaux
            inférieurs de gestion du système.
        </description>
    </section>
    <section>
        <head>Anti-SPAM</head>
        <description>
            Si cette option est activée, il est possible de définir si on veut activer la fonction Anti-SPAM
            sur les messages entrants ou sortants. Il est possible de changer cette option par défaut aux niveaux
            inférieurs de gestion du système.
            Cette option n'est pas activée par défaut.
        </description>
    </section>
    <section>
        <head>Réglage des scores de Spam</head>
        <description>
			Ces deux options permettent de définir le niveau de déclenchement des filtres anti-spam. 
			Le "Score de base" défini le niveau à partir duquel un message pourra être considéré comme un SPAM. 
			A ce niveau, le message sera mis en quarantaine si le système anti-spam utilise le logiciel Mailscanner. 
			Le second niveau "Score limite", défini le niveau à partir duquel le message sera considéré comme un SPAM 
			devant être directement supprimé sans mise en quarantaine ni avertissement. Son score étant considéré
			comme suffisamment élevé pour qu'il n'y ait aucun risque de faux positif.
        </description>
    </section>    
    <section>
        <head>Statut</head>
        <description>
            Cette option permet de renseigner le statut du site. "Actif" veut dire que tout est normal
            et que le site est pleinement fonctionnel. "Verrouillé" veut dire que les utilisateurs ne pourront
            recevoir aucun message (que ce soit par POP3 ou IMAP). Les messages seront quand même enregistré dans
            le système (dans la limite des quotas) mais ils ne seront pas accessible aux utilisateurs.
            "Verrouillé &amp; Rebond" correspond à "Verrouillé" avec en plus le fait que les expéditeurs recevront un
            message les informants que les utilisateurs ne sont pas joignables.
        </description>
    </section>
</help>

=== stefaweb/XAMS-0.3.x/gui/i18n/french/help/templates.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE help SYSTEM "../../../include/dtd/help.dtd">
<help title="Vue générale des gabarits" xams-release="0.0.19" file-release="0.0.9" file-revision="1" date="2008-12-30">
    <lngspec name="french" iso="fr" localname="french"/>
    <skindir>{{skindir}}</skindir>
    <maintainers>
        <maintainer>
            <name>ACTION-WEB</name>
            <email>xams@actionweb.fr</email>
        </maintainer>
    </maintainers>    
    <information>
        Un gabarit est un système très puissant qui permet de définir des praramètres par
        défaut lors de la création de site ou d'utilisateur. Ceci est très utile pour automatiser
        la création de site ou d'utilisateur qui ont souvent la même structuration. Les gabarits créé par d'autres
        utilisateurs ne sont pas visible.
    </information>
    <section>
        <head>Gabarit de site</head>
        <description>
            Vous permet de créer les gabarits pour les sites. Il est aussi possible de les modifier
            et de les effacer.
        </description>
    </section>
    <section>
        <head>Gabarit d'utilisateur</head>
        <description>
            Vous permet de créer les gabarits pour les utilisateurs. Il est aussi possible de les modifier
            et de les effacer.
        </description>
    </section>
</help>
