=== stefaweb/XAMS-0.3.x/gui/include/dtd/help.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT maintainers (maintainer+)>
<!ELEMENT maintainer (name, email)>
<!ATTLIST information
    usertype CDATA "0"
    minusertype CDATA "0"
>
<!ELEMENT information (#PCDATA)>
<!ELEMENT head (#PCDATA)>
<!ELEMENT condition (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ATTLIST section
    usertype CDATA "0"
    minusertype CDATA "0"
>
<!ELEMENT section (head, condition?, description)>
<!ATTLIST lngspec
    name CDATA #REQUIRED
    iso CDATA #REQUIRED
    localname CDATA #REQUIRED
>
<!ELEMENT lngspec EMPTY>
<!ELEMENT skindir (#PCDATA)>
<!ATTLIST help
    title CDATA #REQUIRED
    xams-release CDATA #REQUIRED
    file-release CDATA #REQUIRED
    file-revision CDATA #REQUIRED
    date CDATA #REQUIRED
>
<!ELEMENT help (lngspec, skindir, maintainers, information?, section+)>

=== stefaweb/XAMS-0.3.x/gui/i18n/german/help/dns_zone.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE help SYSTEM "../../../include/dtd/help.dtd">
<help title="DNS Verwaltung" xams-release="0.0.9" file-release="0.0.9" file-revision="1" date="2002-11-31">
    <lngspec name="german" iso="de" localname="deutsch"/>
    <skindir>{{skindir}}</skindir>
    <maintainers>
        <maintainer>
            <name>XAMS Core-Team</name>
            <email>info@xams.org</email>
        </maintainer>
    </maintainers>
    <information>
        Die DNS-Verwaltung von XAMS erlaubt es dem Administrator einen
        Domain-Name-Server komfortabel zu administrieren. Basiswissen
        sollte hier jedoch unbedingt vorhanden sein, da die dafür nötigen
        Einstellungen hier nur kurz angesprochen werden.
        Um den Sachverhalt dennoch einigermaßen verständlich darzustellen,
        sind Beispiele aus dem praktischen Umfeld angegeben, wie z.B. die
        entsprechenden Werte der Zone "xams.org".
    </information>
    <section>
        <head>Zonen-Typ</head>
        <description>
            Für die Errichtung einer Zone muss der Name-Server wissen,
            welchen Typ die Zone darstellt, in wessen Verantwortung die
            Zone liegt. Wird dieser Wert auf "Master" (=primärer DNS) gestellt,
            so geht der Name-Server davon aus, dass er die Verantwortung
            für diese Zone trägt. Der Wert "Slave" bestimmt den DNS
            als sekundären Name-Server, der die Zone von einem anderen
            (primären/Master) DNS bezieht.
            Steht der Wert jedoch auf "Dummy", so findet der Eintrag keine
            Wirkung beim DNS und bleibt unberücksichtigt.
        </description>
    </section>
    <section>
        <head>Zone</head>
        <description>
            Eine Zone ist eine Art Behälter für einen bestimmten Namensraum -
            einen Teil einer Domain und ggf. derer Subdomains. Verwaltet
            bspw. einer Nameserver die Domain "xams.org" so verwaltet er
            automatisch alle Subdomains von "xams.org" wie z.B. "www.xams.org",
            oder "demo.xams.org". Die Zone hierbei ist die "xams.org", welche
            wiederum eine Art Subdomain der Zone "org" darstellt, die beim
            entsprechenden Domain-Registrar liegt.
        </description>
    </section>
    <section>
        <head>Primärer DNS</head>
        <description>
            Dieses Feld muss den primären (Master) Nameserver für die
            angegebene Zone enthalten. Dabei ist zu beachten, dass dieser
            Eintrag einen angehängten Punkt benötigt, insofern dieser
            nicht ein Teil der Zone selbst ist. Im Falle von "xams.org" ist
            dieser Eintrag "sitixns.de.".
        </description>
    </section>
    <section>
        <head>Zonen-Admin (eMail)</head>
        <description>
            In diesem Feld muss die eMail-Adresse des für die Zone
            verantwortlichen Administrators eingetragen werden. Anstatt
            des "@"-Zeichen muss hierbei ein Punkt verwendet werden. Wie
            schon beim Primären DNS muss auch hier wiederum ein Punkt
            angehängt werden, wenn die Domain der eMail-Adresse nicht die
            Zone selbst ist. Die eMail-Adresse "hostmaster@sitixns.de" würde
            also wie folgt abgebildet werden: "hostmaster.sitixns.de.".
            Hinweis: Es können keine eMail-Adresse verwendet werden in dem
            der Teil vor dem "@"-Zeichen (der local Part) selbst einen
            Punkt enthält.
        </description>
    </section>
    <section>
        <head>Serien-Nr.</head>
        <description>
            Jede Zone benötigt eine eindeutige Serien-Nr. Wichtig hierbei
            ist eigentlich nur, dass die Zahl bei jeder Änderung der Zone
            erhöht wird, damit die replizierenden Nameserver die Änderung
            erkennen können. Es hat sich als sehr praktisch erwiesen für
            diese Zahl einfach das aktuelle Datum zzgl. einer zweistelligen
            Ziffer zu nehmen, also 2002072101 für das Jahr 2002, den Monat
            Juli, den 21ten Tag in diesem Monat und den 01ten Eintrag an
            diesem Tag.
        </description>
    </section>
    <section>
        <head>Automatisch</head>
        <description>
            Da ist i.d.R. keinen Sinn macht, die Serien-Nr. per Hand zu
            pflegen, kann dies auch von XAMS automatisch verwaltet werden.
            Es gibt eigentlich kaum Gründe, diese Funktion zu deaktivieren.
        </description>
    </section>
    <section>
        <head>Lebensdauer (TTL)</head>
        <description>
            Die Lebensdauer (engl. Time to Lieve - TTL) dient zur Festlegung, wie lange ein
            Client die Informationen über die Zone zwischenspeichern (cachen)
            darf. Ein niedriger Wert hat den Vorteil, dass Änderungen an
            der Zone sehr schnell (höchstens die gesamte TTL-Zeit) aktiv
            werden, jedoch den Nachteil dass der Nameserver bei oft
            angefragten Zonen wesentlich häufiger um Auskunft gebeten wird.
            Ein sinnvoller Wert hierfür liegt normalerweise bei einem Tag.
        </description>
    </section>
    <section>
        <head>Aktualisierung (Refresh)</head>
        <description>
            Dieser Wert bestimmt, in welchen Intervallen der sekundäre (slave)
            Nameserver die Zone aktualisieren soll.
            Ein sinnvoller Wert hierfür liegt normalerweise bei drei Stunden.
        </description>
    </section>
    <section>
        <head>Erneuter Versuch (Retry)</head>
        <description>
            Gelingt es dem sekundären (slave) Nameserver nicht, nach der unter
            Refresh angegebenen Zeit die Zone zu aktualisieren, so bestimmt
            dieser Wert nach welcher Zeit er sein Vorhaben wiederholen soll.
            Ein sinnvoller Wert hierfür liegt normalerweise bei einer Stunde.
        </description>
    </section>
    <section>
        <head>Abgelaufen (Expire)</head>
        <description>
            Kann einer sekundärer (slave) Nameserver die Zone nicht
            aktualisieren, so erklärt er seine Daten nach der hier angegebenen
            Zeit für ungültig und gibt keine Auskunft mehr über diese Zone.
            Ein sinnvoller Wert hierfür liegt normalerweise bei einer Woche.
        </description>
    </section>
    <section>
        <head>Negative Lebensdauer (Negative TTL)</head>
        <description>
            Zonen-Daten (z.B. Subdomains) die von einem Client angefordert
            werden und nicht existieren, werden höchstens so lange als
            "Misserfolg" zwischengespeichert, wie es dieser Wert angibt.
            Ist die Zeitspanne abgelaufen, so wird wieder aktiv versucht
            die Daten aufzulösen (auf deren Existenz prüfen).
            Ein sinnvoller Wert hierfür liegt normalerweise bei eine Tag.
        </description>
    </section>
</help>

=== stefaweb/XAMS-0.3.x/gui/i18n/english/help/customer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE help SYSTEM "../../../include/dtd/help.dtd">
<help title="Customer Management" xams-release="0.0.9" file-release="0.0.9" file-revision="1" date="2002-11-29">
    <lngspec name="english" iso="en" localname="english"/>
    <skindir>{{skindir}}</skindir>
    <maintainers>
        <maintainer>
            <name>XAMS Core-Team</name>
            <email>info@xams.org</email>
        </maintainer>
    </maintainers>    
    <information>
        A Reseller (resp. Administrator) assigns any desired sites 
        to a Customer. These sites then can be administrated by the Customer.
        Here, he has to keep to the limitations given by the Reseller (resp.
        Administrator). He may apply - according to the limits - any desired
        users or aliases and also manage them.
        In contrast to the Reseller, he cannot gain access to the users or
        aliases belonging to another Customer of course.
    </information>
    <section>
        <head>Customer Name</head>
        <description>
            This is the Name of the Customer as it is e.g. shown
            in the Event-Log.
        </description>
    </section>
    <section>
        <head>Customer Password</head>
        <description>
            In conjunction with the Name and this Password, the Customer
            can login to the XAMS GUI.
        </description>
    </section>
    <section>
        <head>Account locked</head>
        <description>
            Using this option, an Administrator or a Reseller
            can lock a Customer. Thereby he can't login the XAMS
            GUI anymore.
        </description>
    </section>
    <section>
        <head>Reseller</head>
        <description>
            Here, the Customer is assigned to a specific Reseller.
            Depending on the Reseller, the Site-selection changes
            to the pool that this Reseller administrates.
        </description>
    </section>
    <section>
        <head>Sites</head>
        <description>
            Here, a Administrator resp. a Reseller can assign
            one or several Sites to a Customer.
            But only the Sites that are available to the
            Reseller can be assigned to his Customer.
        </description>
    </section>
</help>

=== stefaweb/XAMS-0.3.x/gui/i18n/german/help/administrator.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE help SYSTEM "../../../include/dtd/help.dtd">
<help title="Administrator Verwaltung" xams-release="0.0.9" file-release="0.0.9" file-revision="1" date="2002-11-31">
    <lngspec name="german" iso="de" localname="deutsch"/>
    <skindir>{{skindir}}</skindir>
    <maintainers>
        <maintainer>
            <name>XAMS Core-Team</name>
            <email>info@xams.org</email>
        </maintainer>
    </maintainers>
    <information>
        Ein Administrator kann ohne jegliche Einschränkungen in
        sämtlichen Daten Änderungen vornehmen. Er besitzt
        vollständigen Zugriff auf alle Funktionen von XAMS und kann
        somit problemlos alle Wiederverkäufer und ggf. auch deren
        Endkunden verwalten.
    </information>
    <section>
        <head>Administrator Name</head>
        <description>
            Dies ist der Name des Administrators, so wie er bspw. auch
            im Ereignis-Log erscheint. Beim Login muss diesem Namen
            ein "adm_" vorangestellt werden, damit XAMS weiß um welche
            Art Benutzer es sich handelt.
        </description>
    </section>
    <section>
        <head>Administrator Passwort</head>
        <description>
            In Verbindung mit dem Namen und diesem Passwort, kann sich ein
            Administrator an der XAMS GUI anmelden.
        </description>
    </section>
    <section>
        <head>Konto gesperrt</head>
        <condition>not_himself</condition>
        <description>
            Mit dieser Option kann ein Administrator andere Administratoren
            sperren. Dadurch können sich diese nicht mehr an der XAMS
            GUI anmelden.
        </description>
    </section>
</help>

=== stefaweb/XAMS-0.3.x/gui/i18n/english/help/dns_zone.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE help SYSTEM "../../../include/dtd/help.dtd">
<help title="DNS Management" xams-release="0.0.9" file-release="0.0.9" file-revision="1" date="2002-11-29">
    <lngspec name="english" iso="en" localname="english"/>
    <skindir>{{skindir}}</skindir>
    <maintainers>
        <maintainer>
            <name>XAMS Core-Team</name>
            <email>info@xams.org</email>
        </maintainer>
    </maintainers>    
    <information>
        The DNS-Management of XAMS allows you to comfortable administrate
        your Domain server. You should already know something about DNS and
        howto configure a BIND nameserver, because we cannot fully explain every
        setting.
        We have added some examples like the Zone "xams.org", to show you what
        it supposed to be entered at each setting.
    </information>
    <section>
        <head>Zone Type</head>
        <description>
            To setup a zone, a nameserver must know which type the zone has,
            and who is responsible for that zone.
            Setting it to "Master" (= primary DNS), makes your nameserver responsible
            for the zone. "Slave" makes your nameserver get the zone information off
            another (primary/Master) DNS.
            Setting it to "Dummy", has no effect for your DNS because this zone
            wont be exported by the zone-file generation script.
        </description>
    </section>
    <section>
        <head>Zone</head>
        <description>
            A Zone is a kind of a container for a namespace - a part of a domain
            or subdomain. If your Nameserver manages the zone "xams.org" it also
            manages all subdomains of "xams.org" like e.g. "www.xams.org" or "demo.xams.org".
            The zone "xams.org" can be seen as a subdomain of the zone "org", which is managed
            by a domain-registrar.
        </description>
    </section>
    <section>
        <head>Primary DNS</head>
        <description>
            This field must contain the primary (Master) Nameserver for the given Zone.
            Note that this entry needs a trailing dot, in case it is not a part 
            of the zone itself. In case of "xams.org" it is "sitixns.de.".
        </description>
    </section>
    <section>
        <head>Zone Admin (eMail)</head>
        <description>
            The email-adress of the responsible administrator for the zone
            must be entered here. Note, that instead of the "@"-sign you must
            use a dot. Like with the primary DNS also the trailing dot
            ist needed, when the domain of the email-address isn't a part of the zone.
            The email-address "hostmaster@sitixns.de" would look like "hostmaster.sitixns.de.".
            Note: you cannot use email addresses that have dot within their local part (before
            the "@" sign).
        </description>
    </section>
    <section>
        <head>Serial</head>
        <description>
            Every zone needs a unique serial. The most important thing here is
            that the number increases with every change to the zone, so that the
            secondary DNS figure out that something has changed.
            It is common use to take the current date and add a 2 digit serial. e.g.
            2002072101 stands for Year 2002, Month Juli, Day 21st the 01st entry/change
            on that day.
        </description>
    </section>
    <section>
        <head>Automatic</head>
        <description>
            Normally it ist not useful to edit the serialnumber by hand, xams can do this for you.
            There're only few reasons why this feature should be deactivated.
        </description>
    </section>
    <section>
        <head>Time to Live (TTL)</head>
        <description>
            Time-To-Live (TTL) sets how long a client is allowed to cache the informations
            of your zone. A low value has the advantage, that changes get active very fast,
            the disadvantage ist that your nameserver gets asked more often. A meaningful value is
            usually one day.
        </description>
    </section>
    <section>
        <head>Refresh</head>
        <description>
            This value sets the interval the secondary (slave) nameserver uses to actualize
            the Zone. A meaningful value is usually three hours.
        </description>
    </section>
    <section>
        <head>Retry</head>
        <description>
            If the secondary (slave) nameserver doesn't succeed in refreshing the zone
            information, then this value sets the time the server waits until he retries.
            A meaningful value is usually one hour.
        </description>
    </section>
    <section>
        <head>Expire</head>
        <description>
            If a secondary (slave) nameserver cannot actualize a zone, it declares the zone
            invalid after the amount of time set here. It answers no requests for that zone
            after that time.
            A meaningful value is usually one week.
        </description>
    </section>
    <section>
        <head>Negative TTL</head>
        <description>
            Zone data requested by clients that does not exist, is temporary (for time set here)
            stored as failure. After that time the server tries to resolve the data again.
            A meaningful value is usually one day.
        </description>
    </section>
</help>

=== stefaweb/XAMS-0.3.x/gui/i18n/french/help/accounts.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE help SYSTEM "../../../include/dtd/help.dtd">
<help title="Comptes XAMS" xams-release="0.0.19" file-release="0.0.9" file-revision="1" date="2008-12-03">
    <lngspec name="french" iso="fr" localname="french"/>
    <skindir>{{skindir}}</skindir>
    <maintainers>
        <maintainer>
            <name>ACTION-WEB</name>
            <email>xams@actionweb.fr</email>
        </maintainer>
    </maintainers>
        <information>
        XAMS atteint un maximum de flexibilité et de fonctionnalité dans l'administration
        d'un système de messagerie en raison de son architecture à 3 niveaux, à savoir :
        "administrateurs", "revendeurs" et "clients".
    </information>
    <section>
        <head>Administrateurs</head>
        <description>
            Un administrateur peut effectuer des changements sur toutes les données sans
            aucune limitation. Il a accès total à l'ensemble de toutes les fonctions de XAMS
            et peut administer ainsi tous les revendeurs et si nécessaire intervenir même
            sur les données des clients.
        </description>
    </section>
    <section>
        <head>Revendeurs</head>
        <description>
            L'administrateur assigne tous les sites clients désirés à un revendeur. Ces sites
            peuvent alors être administré par ce revendeur qui doit s'en tenir aux limitations
            données par l'administrateur.
            
            Il peut effectuer des changements - selon les limites définies - sur tous ses clients
            et également les contrôler. Contrairement à l'administrateur, il ne peut pas effectuer
            des changements sur les préférences du système, sur les configurations du Carnet d'Addresse,
            et il ne lui est pas possible d'analyser la base de données. En plus de cela, il ne peut
            naturellement pas accéder aux clients appartenant à un autre revendeur.
        </description>
    </section>
    <section>
        <head>Clients</head>
        <description>
            Un revendeur (sous la responsabilité d'un administrateur) assigne des sites à un
            client. Ces sites peuvent ensuite être administré par le client. Il peut effectuer
            des changements - selon les limites définies par le revendeur et l'administrateur -
            sur tous ses utilisateurs ou ses alias, et également les contrôler.
            Le client ne peut naturellement pas accéder aux utilisateurs ou alias d'un autre client.
        </description>
    </section>
</help>

=== stefaweb/XAMS-0.3.x/gui/i18n/french/help/customer_reseller.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE help SYSTEM "../../../include/dtd/help.dtd">
<help title="Assignation des revendeurs" xams-release="0.0.19" file-release="0.0.9" file-revision="1" date="2008-12-03">
    <lngspec name="french" iso="fr" localname="french"/>
    <skindir>{{skindir}}</skindir>
    <maintainers>
        <maintainer>
            <name>ACTION-WEB</name>
            <email>xams@actionweb.fr</email>
        </maintainer>
    </maintainers>
    <information>
        Chaque client peut être assigné à un revendeur spécifique. Grace à cela,
        XAMS est capable d'attribuer les quotas revendeurs aux clients qui lui dépendent.
        Le quota revendeur peut être réduit par la somme de tous les quotas des clients
        et des sites.
    </information>
    <section>
        <head>Revendeur</head>
        <description>
            Sélectionnez ici le revendeur dont dépendra ce client.
        </description>
    </section>
</help>

=== stefaweb/XAMS-0.3.x/gui/i18n/english/help/user.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE help SYSTEM "../../../include/dtd/help.dtd">
<help title="User Management" xams-release="0.0.16" file-release="0.0.9" file-revision="1" date="2004-05-18">
    <lngspec name="english" iso="en" localname="english"/>
    <skindir>{{skindir}}</skindir>
    <maintainers>
        <maintainer>
            <name>XAMS Core-Team</name>
            <email>info@xams.org</email>
        </maintainer>
    </maintainers>
    <information>
        The user is simply expressed by the portion of an e-mail address before
        the @ symbol. Presently, a "user" in XAMS represents nothing more than an
        e-mail account.
        A user who wants to send and/or receive e-mail via a mail client (MUA) has to
        specify the entire e-mail address for the login/username.
        It should be noted that a user has as many e-mail addresses as domains
        contained in the respective site. (For example: the site "firm_name" contains
        the domains "firm_name.com" and "firm_name.net" as well as user "foo" and
        "bar". Both of the users have thereby two e-mail accounts: "foo@firm_name.com",
        "foo@firm_name.net" as well as "bar@firm_name.com" and "bar@firm_name.net".)
    </information>
    <section>
        <head>Site</head>
        <description>
            This section is used to designate which site the new user should belong to.
            While the user gets a "virtual" e-mail address for every domain contained
            in this site, they only have a single "real" mailbox.
        </description>
    </section>
    <section>
        <head>Account name (E-Mail)</head>
        <description>
            This is the E-Mail address for the user, representing the portion of the e-mail
            address before the domain.
        </description>
    </section>
    <section>
        <head>Unique Login name (optional)</head>
        <description>
            Optionally, you may define a "Unique Login name" with which a user can use to
            authenticate themselves (instead of using the complete e-mail address).
            This feature is useful for administrators that have to migrate from
            another mail server system and do not want to require all the users
            to update their client configurations. This feature is only recommended for
            those who fall in this latter category.
        </description>
    </section>
    <section>
        <head>Password</head>
        <description>
            With this password the user can log in to receive and send messages.
            Also, the user can - if permitted by the XAMS configuration - change his
            or her password after logging in to the XAMS system.
        </description>
    </section>
    <section>
        <head>Quota</head>
        <description>
            This is the amount of disk space a user's mailbox is allowed to store.
            Messages that would cause a mailbox to exceed this quota will be discarded,
            with the original sender receiving an appropriate error notification.
            The user-level quota can be lower -- but not higher -- than the site-level
            setting. A site admin cannot allocate more disk space to users than the site's
            quota allows.
        </description>
    </section>
    <section>
        <head>Type</head>
        <description>
            This configures which protocols users can use to receive messages. This
            setting can be changed at any time. If IMAP access is granted but later
            withdrawn, any server-side mail boxes will be removed and no longer accessible
            by the previous owners.
        </description>
    </section>
    <section>
        <head>Virus check (Incoming / Outgoing)</head>
        <description>
            With this option you can indicated whether both incoming and outgoing
            messages for this user should be checked for viruses (by an external program).
        </description>
    </section>
    <section>
        <head>Spam check (Incoming / Outgoing)</head>
        <description>
            With this option you can indicated whether both incoming and outgoing
            messages for this user should be checked for spam (by an external program).
        </description>
    </section>
    <section>
        <head>Relay on auth</head>
        <description>
            This option allows the user to send messages over SMTP via this server,
            provided the user authenticates with the same username and password used
            for receiving mail. If the SMTP server is operated as an open relay (i.e., no
            authentication required and anyone can send mail through the server) this
            option is ignored.
        </description>
    </section>
    <section>
        <head>Relay on check</head>
        <description>
            This option allows the user to send messages over SMTP via this server,
            provided the user first receives messages via authenticated POP or IMAP.
            This feature is also known as "check before send," "SMTP-after-POP," and
            "SMTP-after-IMAP." If the SMTP server is operated as an open relay (i.e., no
            authentication required and anyone can send mail through the server) this
            option is ignored.
        </description>
    </section>
    <section>
        <head>Status</head>
        <description>
            This function provides information about the user's status. Active refers to
            normal user privileges without limitations. Locked means a user can no longer
            retrieve any e-mail messages (neither via POP nor IMAP), although messages
            addressed to this user will still be saved and stored (provided there is
            sufficient disk space remaining in the user's quota). Locked &amp; Bounce
            takes this a step further: in this case the mail server will pretend that the
            user does not exist and will generate a bounce-message for the original sender
            indicating that the user is not reachable.
        </description>
    </section>
    <section>
        <head>Filter</head>
        <description>
            This menu is used to configure user-specific filter settings.
        </description>
    </section>
</help>
