=== stefaweb/XAMS-0.3.x/gui/include/dtd/help.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT maintainers (maintainer+)>
<!ELEMENT maintainer (name, email)>
<!ATTLIST information
    usertype CDATA "0"
    minusertype CDATA "0"
>
<!ELEMENT information (#PCDATA)>
<!ELEMENT head (#PCDATA)>
<!ELEMENT condition (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ATTLIST section
    usertype CDATA "0"
    minusertype CDATA "0"
>
<!ELEMENT section (head, condition?, description)>
<!ATTLIST lngspec
    name CDATA #REQUIRED
    iso CDATA #REQUIRED
    localname CDATA #REQUIRED
>
<!ELEMENT lngspec EMPTY>
<!ELEMENT skindir (#PCDATA)>
<!ATTLIST help
    title CDATA #REQUIRED
    xams-release CDATA #REQUIRED
    file-release CDATA #REQUIRED
    file-revision CDATA #REQUIRED
    date CDATA #REQUIRED
>
<!ELEMENT help (lngspec, skindir, maintainers, information?, section+)>

=== stefaweb/XAMS-0.3.x/gui/i18n/french/help/search.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE help SYSTEM "../../../include/dtd/help.dtd">
<help title="Recherche" xams-release="0.0.19" file-release="0.0.9" file-revision="1" date="2008-12-03">
    <lngspec name="french" iso="fr" localname="french"/>
    <skindir>{{skindir}}</skindir>
    <maintainers>
        <maintainer>
            <name>ACTION-WEB</name>
            <email>xams@actionweb.fr</email>
        </maintainer>
    </maintainers>
    <information>
        La fonction de recherche de XAMS vous permet d'effectuer des recherches sur les sites,
        les domaines, les utilisateurs ou les alias en utilisant différent critères de recherche.
    </information>
    <section>
        <head>Nom du site</head>
        <description>
            Ce champ peut contenir le nom d'un site. Il doit être un nom de site unique tel qu'il
            a été défini par un administrateur ou un revendeur. Un revendeur ou un client peuvent utiliser
            le système de recherche mais les résultats dépendrons de leur droits d'accès aux différents sites,
            clients ou utilisateurs.
        </description>
    </section>
    <section>
        <head>Quota maximum en KB (par utilisateur)</head>
        <description>
            Cette valeur contient la taille maximum en KB pour une boîte aux lettres de messagerie
            pour un utilisateur. Tout message reçu dépassant cette taille sera refusé par le système
            et un message d'erreur envoyé à l'expéditeur. Il est bien sûr possible de configurer
            spécifiquement la taille d'une boîte aux lettre d'un utilisateur avec une valeur inférieure
            mais celle-ci ne pourra excéder la valeur définie.
        </description>
    </section>
    <section>
        <head>Nbr. maximum d'utilisateur</head>
        <description>
            La limite maximum d'utilisateur qu'un site est autorisé à utiliser.
        </description>
    </section>
    <section>
        <head>Nbr. maximum d'alias</head>
        <description>
            La limite maximum d'alias qu'un site est autorisé à utiliser.
        </description>
    </section>
    <section>
        <head>Nom du domaine</head>
        <description>
             Recherche par domaine (exemple : xams.org).
        </description>
    </section>
    <section>
        <head>Nom du compte</head>
        <description>
            Le compte de messagerie d'un utilisateur (la partie gauche avant le "@").
        </description>
    </section>
    <section>
        <head>Adresse E-Mail</head>
        <description>
            L'adresse de messagerie électronique complete d'un utilisateur.
        </description>
    </section>
    <section>
        <head>Alias (partie gauche)</head>
        <description>
            La partie avant le signe "@" qui compose un Alias.
        </description>
    </section>
    <section>
        <head>Alias (partie droite)</head>
        <description>
            La partie après le signe "@" qui compose un Alias. Vous pouvez aussi saisir plusieurs adresses
            en les séparant par des virgules.
        </description>
    </section>
</help>

=== stefaweb/XAMS-0.3.x/gui/i18n/german/help/templates.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE help SYSTEM "../../../include/dtd/help.dtd">
<help title="Vorlagen Übersicht" xams-release="0.0.9" file-release="0.0.9" file-revision="1" date="2002-11-31">
    <lngspec name="german" iso="de" localname="deutsch"/>
    <skindir>{{skindir}}</skindir>
    <maintainers>
        <maintainer>
            <name>XAMS Core-Team</name>
            <email>info@xams.org</email>
        </maintainer>
    </maintainers>
    <information>
        Mit den Vorlagen bietet XAMS eine äußerst anwenderfreundliche
        Funktion, Benutzer beim anlegen diverser Konten mit
        persönlich für ihn gespeicherten Vorgaben zu unterstützen.
        Häufig müssen Sites oder eMail-Adressen nach gleichem oder
        zumindest ähnlichem Schema angelegt werden. Ist vorauszusehen,
        dass dies der Fall ist, so kann von vornherein eine Vorlage
        hierfür eingerichtet werden um dann mit dieser den Vorgang
        der Konten-Erstellung zu beschleunigen.
        Hierbei ist zu beachten, dass für jeden Benutzer
        (gleichgültig ob Administrator, Wiederverkäufer oder Endkunde)
        eigene Vorlagen gespeichert werden - die Nutzung von Vorlagen
        anderer Benutzer ist nicht möglich.
    </information>
    <section>
        <head>Site Vorlagen</head>
        <description>
            Hier können Vorlagen für Sites erstellt, bearbeitet, gelöscht
            oder angewendet werden.
        </description>
    </section>
    <section>
        <head>Benutzer Vorlagen</head>
        <description>
            Hier können Vorlagen für Benutzer erstellt, bearbeitet, gelöscht
            oder angewendet werden.
        </description>
    </section>
</help>

=== stefaweb/XAMS-0.3.x/gui/i18n/german/help/preferences.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE help SYSTEM "../../../include/dtd/help.dtd">
<help title="Einstellungen" xams-release="0.0.9" file-release="0.0.9" file-revision="1" date="2002-11-31">
    <lngspec name="german" iso="de" localname="deutsch"/>
    <skindir>{{skindir}}</skindir>
    <maintainers>
        <maintainer>
            <name>XAMS Core-Team</name>
            <email>info@xams.org</email>
        </maintainer>
    </maintainers>
    <information>
        Bestimmte Einstellungen von XAMS, deren Sicherheit hierdurch nicht
        gefährdet sind, können direkt innerhalb der grafischen Oberfläche
        vorgenommen werden.
    </information>
    <section>
        <head>Begrüßung beim Login</head>
        <description>
            Der Willkommensgruß beim Login (Standard ist "Welcome to XAMS")
            kann hier geändert oder deaktiviert (leeres Feld) werden.
        </description>
    </section>
    <section>
        <head>Standard-Länge der Ereignis-Anzeige</head>
        <description>
            Dieser Wert bestimmt über die Anzahl der Zeilen die in der
            Ereignis-Anzeige standardmäßig angezeigt werden. Je nach
            Bildschirm-Auflösung bzw. Fenster-Größe kann hier ein optimaler
            Wert eingestellt werden.
        </description>
    </section>
    <section>
        <head>Online 'Über XAMS'</head>
        <description>
            Es besteht die Möglichkeit, dass Menü "Über XAMS" über das
            Internet von der xams.org Seite anzufordern. Der Vorteil besteht
            in einer aktuelleren Seite, die ggf. auch über besondere
            Neuigkeiten (z.B.   Sicherheitslücken) informieren kann.
        </description>
    </section>
    <section>
        <head>Auf neue Version prüfen</head>
        <description>
            Diese Option bietet die Möglichkeit über das Internet zu
            prüfen, ob es eine neue Version von XAMS gibt.  Ist dies der Fall,
            so wird dies einem Administrator nach erfolgreichem Login angezeigt.
        </description>
    </section>
    <section>
        <head>Standard Sprache</head>
        <description>
            Legt die Standardsprache von XAMS fest. Diese kann natürlich
            weiterhin beim Login umgestellt werden.
        </description>
    </section>
</help>

=== stefaweb/XAMS-0.3.x/gui/i18n/french/help/site_addressbook.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE help SYSTEM "../../../include/dtd/help.dtd">
<help title="Administration des Carnets d'adresse de Site" xams-release="0.0.19" file-release="0.0.9" file-revision="1" date="2008-12-03">
    <lngspec name="french" iso="fr" localname="french"/>
    <skindir>{{skindir}}</skindir>
    <maintainers>
        <maintainer>
            <name>ACTION-WEB</name>
            <email>xams@actionweb.fr</email>
        </maintainer>
    </maintainers>    
    <information>
        Le Carnet d'Adresse XAMS est disponible pour créer des Carnet d'Adresse
        pour les sites, les utilisateurs, les alias, le revendeurs et les clients.
        Les champs du Carnet d'Adresse (nom, rue, ville, etc.) doivent être créé
        par vous même en fonction de vos propres besoins.
    </information>
    <section>
        <head>Nom du champ</head>
        <description>
            Entrer ici le nom du champ qui sera disponible dans votre Carnet d'Adresse.
        </description>
    </section>
    <section>
        <head>LDAP</head>
        <description>
            Avec LDAP (Lightweight Directory Access Protocol) XAMS offre la possibilité
            d'exporter l'ensemble des champs dans ce type de base de données. Cette base 
            de données LDAP peut être utilisé de manière globale par d'autres types
            d'application compatible LDAP.
        </description>
    </section>
    <section>
        <head>ACL Rvendeur</head>
        <description>
            L'ACL Revendeur (Access Control List) est utilisé pour limiter des revendeurs
            à certain champs. L'option "aucun" neutralise tous les accès pour ce revendeur
            (en lecture et en écriture). Les options "lecture" et "écriture" autorise le
            revendeur à lire ou modifier le contenu de ce champ.
        </description>
    </section>
    <section>
        <head>ACL Client</head>
        <description>
            Comportement identique au ACL Revendeur. Vous pouvez définir avec cette fontion
            l'accès pour vos clients.
        </description>
    </section>
    <section>
        <head>Déplacer le champ</head>
        <description>
            Cette fonction change l'ordre d'apparition d'un champ dans l'interface.
            Le menu défilant contient la liste de tous les champs existant. Vous pouvez
            sélectionner un des champs dans cette liste pour déplacer le champ sélectionné
            dans la liste.
        </description>
    </section>
    <section>
        <head>Effacer</head>
        <description>
            Si vous sélectionnez cette option pour une ligne et que vous cliquez ensuite
            sur "Mettre à jour", vous supprimez la ligne de la base. Attention : toutes les
            données de ce champ seront définitivement détruite.
        </description>
    </section>
</help>

=== stefaweb/XAMS-0.3.x/gui/i18n/english/help/administrator.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE help SYSTEM "../../../include/dtd/help.dtd">
<help title="Administrator Management" xams-release="0.0.9" file-release="0.0.9" file-revision="1" date="2002-11-29">
    <lngspec name="english" iso="en" localname="english"/>
    <skindir>{{skindir}}</skindir>
    <maintainers>
        <maintainer>
            <name>XAMS Core-Team</name>
            <email>info@xams.org</email>
        </maintainer>
    </maintainers>    
    <information>
        An Administrator can take up changes on all data without
        any limitations. He has total access to every function of XAMS and thus
        can administrate all Resellers and where required even whose Customers.
    </information>
    <section>
        <head>Administrator Name</head>
        <description>
            This is the Name of the Administrator as it is e.g. shown
            in the Event-Log. At login this name has to be prefixed by
            "adm_", so that XAMS knows wich kind of user it has to
            validate.
        </description>
    </section>
    <section>
        <head>Administrator Password</head>
        <description>
            In conjunction with the Name and this Password, the Administrator
            can login to the XAMS GUI.
        </description>
    </section>
    <section>
        <head>Account locked</head>
        <condition>not_himself</condition>
        <description>
            Using this option, an Administrator can lock other
            Administrators. Thereby he can't login the XAMS
            GUI anymore.
        </description>
    </section>
</help>

=== stefaweb/XAMS-0.3.x/gui/i18n/french/help/administrator.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE help SYSTEM "../../../include/dtd/help.dtd">
<help title="Administrateurs XAMS" xams-release="0.0.19" file-release="0.0.9" file-revision="1" date="2008-12-03">
    <lngspec name="french" iso="fr" localname="french"/>
    <skindir>{{skindir}}</skindir>
    <maintainers>
        <maintainer>
            <name>ACTION-WEB</name>
            <email>xams@actionweb.fr</email>
        </maintainer>
    </maintainers>
    <information>
        Un administrateur peut effectuer des modifications sur toutes les données
        du système sans acune limitation. Il a un accès total à chacune des fonctions
        de XAMS et de par la même, peut administrer les revendeurs, et si nécessaire
        les clients de ceux-ci.
    </information>
    <section>
        <head>Nom de l'administrateur</head>
        <description>
            C'est le nom de l'administrateur comme il est affiché dans l'écran
            de suivi des logs. A la connexion, ce nom doit être précédé par "adm_"
            pour que le système XAMS sache à quelle type d'utilisateur il a affaire.
        </description>
    </section>
    <section>
        <head>Mot de passe de l'administrateur</head>
        <description>
            Utilisé en même temps que le nom de l'administrateur, le mot de passe est demandé 
            à la connexion pour pouvoir accèder à l'interface d'administration du système XAMS.
        </description>
    </section>
    <section>
        <head>Compte vérouillé</head>
        <condition>not_himself</condition>
        <description>
            Cette option permet à l'administrateur de vérouiller le compte d'autres
            administrateurs les empêchant ainsi de se connecter au système.
        </description>
    </section>
</help>

=== stefaweb/XAMS-0.3.x/gui/i18n/german/help/search.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE help SYSTEM "../../../include/dtd/help.dtd">
<help title="Suche" xams-release="0.0.9" file-release="0.0.9" file-revision="1" date="2002-11-31">
    <lngspec name="german" iso="de" localname="deutsch"/>
    <skindir>{{skindir}}</skindir>
    <maintainers>
        <maintainer>
            <name>XAMS Core-Team</name>
            <email>info@xams.org</email>
        </maintainer>
    </maintainers>
    <information>
        Die XAMS-Suche hilft beim schnellen Auffinden von
        Sites, Domains, Benutzern und Aliasen durch die Möglichkeit
        nach den verschiedensten Suchkriterien zu suchen.
    </information>
    <section>
        <head>Name der Site</head>
        <description>
            Dies ist der Name des Site-Containers. Es muss sich hierbei um
            einen systemweit, eindeutigen Namen handeln, welcher vom
            Administrator oder Wiederverkäufer vergeben wird. Der Reseller
            kann die Verwaltung dieses Containers in die Obhut eines Endkunden
            weitergeben. Die Kontingente der Site kann jedoch nur der
            Administrator bzw. der Wiederverkäufer selbst verwalten.
        </description>
    </section>
    <section>
        <head>Maximales Kontingent in KB (pro Benutzer)</head>
        <description>
            Dies ist die maximale Postfachgröße die ein einzelner Benutzer
            dieser Site in Anspruch nehmen kann. eMails die größer sind, als
            der noch verbleibende Platz, werden nicht gespeichert. Der Absender
            erhält dabei eine entsprechende Fehlermeldung. Des weiteren kann
            ein Endkunde einem Benutzer zwar weniger Speicher, jedoch nicht
            mehr zur Verfügung stellen als ihm dieses Limit vorschreibt.
        </description>
    </section>
    <section>
        <head>Maximale Benutzer</head>
        <description>
            Tragen Sie hier eine Ziffer ein, die die Anzahl der Benutzer
            angibt, die an dieser Site aufgehängt werden können.
        </description>
    </section>
    <section>
        <head>Maximale Aliase</head>
        <description>
            Analog zu "Maximalen Benutzern" wird hier die maximale Anzahl an
            zur Verfügung stehenden Aliases angegeben. Auch diese kann ein
            Endkunde nicht überschreiten.
        </description>
    </section>
    <section>
        <head>Name der Domain</head>
        <description>
             Suchroutine, mit der Domainnamen (z.B. xams.org) gefiltert
             werden können.
        </description>
    </section>
    <section>
        <head>Benutzername</head>
        <description>
            Zeichenkette, i.d.R. die eMail Adresse, mit der sich der Kunde mit
            seinem Postfach verbindet.
        </description>
    </section>
    <section>
        <head>E-Mail Adresse</head>
        <description>
            Geben Sie hier eine eMail Adresse mit der kompletten Syntax an.
        </description>
    </section>
    <section>
        <head>Alias Name (Left Part)</head>
        <description>
            Information, betreffend Zeichen vor dem @-Zeichen.
        </description>
    </section>
    <section>
        <head>Alias Ziel (Right Part)</head>
        <description>
            Dies ist die (Ziel-)Adresse an die die Mails weitergeleitet werden,
            die an den Alias adressiert wurden. Befindet sich die Zieladresse
            in der gleichen Site, so ist nur der Teil vor dem @-Zeichen
            anzugeben - andernfalls die komplette eMail-Adresse. In diesem
            Feld können durch Komma getrennt mehrere Adressen angegeben werden.
        </description>
    </section>
</help>

=== stefaweb/XAMS-0.3.x/gui/i18n/french/help/customer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE help SYSTEM "../../../include/dtd/help.dtd">
<help title="Administration des clients" xams-release="0.0.19" file-release="0.0.9" file-revision="1" date="2008-12-03">
    <lngspec name="french" iso="fr" localname="french"/>
    <skindir>{{skindir}}</skindir>
    <maintainers>
        <maintainer>
            <name>ACTION-WEB</name>
            <email>xams@actionweb.fr</email>
        </maintainer>
    </maintainers>
    <information>
        Un Revendeur (sous la responsabilité d'un Administrateur) assigne des Sites
        à un Client. Ces sites peuvent ensuite être pleinement administrés par le
        client. En fonction des limitations définies par le revendeur (sous la responsabilité
        d'un administrateur), le client peut définir les comptes de messagerie
        et les Alias de ces sites. Il ne peut bien sûr administrer que des utilisateurs
        ou des Alias dont il a la responsabilité.
    </information>
    <section>
        <head>Nom du client</head>
        <description>
            C'est le nom du client tel qu'il apparaît dans XAMS et notamment
            dans les logs.
        </description>
    </section>
    <section>
        <head>Mot de passe du client</head>
        <description>
            Utilisé en même temps que le nom du client, le mot de passe de
            l'administrateur est demandé à la connexion pour pouvoir accèder à
            l'interface d'administration XAMS.
        </description>
    </section>
    <section>
        <head>Compte vérouillé</head>
        <description>
            Cette option permet à l'administrateur ou le revendeur de vérouiller 
            le compte d'un client l'empêchant ainsi de se connecter au système.
        </description>
    </section>
    <section>
        <head>Revendeur</head>
        <description>
            Cette option permet d'assigner un client à un revendeur.
            En fonction du revendeur et de ses attributions, le contenu
            du menu déroulant change.
        </description>
    </section>
    <section>
        <head>Sites</head>
        <description>
            Avec cette option, un revendeur sous la responsabilité
            d'un administrateur peut attribuer un ou plusieurs sites à un client.
            Uniquement les sites disponible pour un revendeur peuvent être
            assigné à ce client.
        </description>
    </section>
</help>
