=== stefaweb/XAMS-0.3.x/gui/include/dtd/i18n.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT maintainers (maintainer+)>
<!ELEMENT maintainer (name, email)>
<!ELEMENT msgs (title, msg+)>
<!ATTLIST title
    id CDATA #REQUIRED
>
<!ATTLIST msg
    id CDATA #REQUIRED
>
<!ELEMENT title (#PCDATA)>
<!ELEMENT msg (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ATTLIST lngspec
    name CDATA #REQUIRED
    iso CDATA #REQUIRED
    localname CDATA #REQUIRED
>
<!ELEMENT lngspec EMPTY>
<!ELEMENT i18n (lngspec, maintainers, msgs)>
<!ATTLIST i18n
    xams-release CDATA #REQUIRED
    file-release CDATA #REQUIRED
    file-revision CDATA #REQUIRED
    date CDATA #REQUIRED
>

=== stefaweb/XAMS-0.3.x/gui/i18n/english/user.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE i18n SYSTEM "../../include/dtd/i18n.dtd">
<i18n xams-release="0.0.19" file-release="0.0.9" file-revision="1" date="2008-12-05">
    <lngspec name="english" iso="en" localname="english"/>
    <maintainers>
        <maintainer>
            <name>XAMS Core-Team</name>
            <email>info@xams.org</email>
        </maintainer>
    </maintainers>
    <msgs>
        <title id="User Management" />
        <msg id="Account Settings" />
        <msg id="User Management" />
        <msg id="Site" />
        <msg id="Account name (E-Mail)" />
        <msg id="Unique Login name (optional)" />
        <msg id="Password" />
        <msg id="Quota" />
        <msg id="Type" />
        <msg id="Viruscheck (Incoming)" />
        <msg id="Viruscheck (Outgoing)" />
        <msg id="Spamcheck (Incoming)" />
        <msg id="Spamcheck (Outgoing)" />
        <msg id="Spam Score Trigger" />
        <msg id="Spam Score" />
        <msg id="High Spam Score" />
        <msg id="Site dependent" />
        <msg id="Relay on auth" />
        <msg id="Relay on check" />
        <msg id="Auto reply" />
        <msg id="Status" />
        <msg id="Filter" />
        <msg id="Active" />
        <msg id="Locked" />
        <msg id="Locked &amp; Bounce" />
        <msg id="User created" />
        <msg id="User last updated" />
        <msg id="This unique username does already exists" />
        <msg id="This username does already exists" />
	<msg id="Forbidden characters in username" />
	<msg id="Forbidden characters in unique name" />
        <msg id="Subject" />
        <msg id="Message" />
        <msg id="Unfortunately no more users can be added. Reseller\'s User-Quota has reached." />
        <msg id="Unfortunately no more users can be added. The site based User-Quota has reached." />
        <msg id="Unfortunately no more users can be added. The site based Quota has reached." />
        <msg id="Unknown error occured." />
        <msg id="Contain non-numeric Characters" />
	<msg id="Field has to be filled out" />
	<msg id="Invalid ID" />
	<msg id="Select a Site in the drop-down menu." />
	<msg id="Site does not allow users having incoming viruscheck." />
	<msg id="Site does not allow users having outgoing viruscheck." />
	<msg id="Site does not allow users having incoming spamcheck." />
	<msg id="Site does not allow users having outgoing spamcheck." />
	<msg id="Selected AddrType is not allowed." />
	
	<!-- Errors function -->
	<msg id="Too short min=('%s')" />
	<msg id="Too long (min='%s')" />
        <msg id="Value is too low (min='%s')" />
	<msg id="Value is too big (max='%s')" />
        
        <!-- Status messages -->
        <msg id="User '%s' was added successfully." />
        <msg id="User '%s' was updated successfully." />
        <msg id="User '%s' was deleted successfully." />
        <msg id="User '%s' could not be added." />
        <msg id="User '%s' could not be updated." />
        <msg id="User '%s' could not be deleted." />
    </msgs>
</i18n>

=== stefaweb/XAMS-0.3.x/gui/i18n/french/user_template.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE i18n SYSTEM "../../include/dtd/i18n.dtd">
<i18n xams-release="0.0.19" file-release="0.1.0" file-revision="1" date="2008-12-03">
    <lngspec name="french" iso="fr" localname="french"/>
    <maintainers>
        <maintainer>
            <name>ACTION-WEB</name>
            <email>xams@actionweb.fr</email>
        </maintainer>
    </maintainers>
    <msgs>
        <title id="User Template Management">Administration des gabarits utilisateur</title>
        <msg id="User-Templates Management">Administration des gabarits utilisateur</msg>
        <msg id="Template-Name">Nom du gabarit</msg>
        <msg id="Username">Nom du compte (E-Mail)</msg>
        <msg id="Password">Mot de passe</msg>
        <msg id="Quota">Quota</msg>
        <msg id="Type">Protocole</msg>
        <msg id="Viruscheck (Incoming)">Anti-Virus (Entrant)</msg>
        <msg id="Viruscheck (Outgoing)">Anti-Virus (Sortant)</msg>
        <msg id="Spamcheck (Incoming)">Anti-SPAM (Entrant)</msg>
        <msg id="Spamcheck (Outgoing)">Anti-SPAM (Sortant)</msg>
        <msg id="Spam Score Trigger">Réglage des scores de Spam</msg>
        <msg id="Spam Score">Score de base </msg>
        <msg id="High Spam Score">Score limite </msg>
        <msg id="Site dependent">Dépendant du site</msg>
        <msg id="Relay on auth">Relais sur autorisation</msg>
        <msg id="Relay on check">Relais sur vérification</msg>
        <msg id="Template created">Gabarit créé le</msg>
        <msg id="Template last updated">Gabarit mis à jour le</msg>

        <!-- Status-Meldungen -->
        <msg id="User-Template '%s' was added successfully.">Le gabarit utilisateur '%s' a été ajouté avec succès.</msg>
        <msg id="User-Template '%s' was updated successfully.">Le gabarit utilisateur '%s' a été mis à jour avec succès.</msg>
        <msg id="User-Template '%s' was deleted successfully.">Le gabarit utilisateur '%s' a été effacé avec succès.</msg>
        <msg id="User-Template '%s' could not be added.">Le gabarit utilisateur '%s' n'a pas pu être ajouté.</msg>
        <msg id="User-Template '%s' could not be updated.">Le gabarit utilisateur '%s' n'a pas pu être mis à jour.</msg>
        <msg id="User-Template '%s' could not be deleted.">Le gabarit utilisateur '%s' n'a pas pu être effacé.</msg>
    </msgs>
</i18n>

=== stefaweb/XAMS-0.3.x/gui/i18n/french/eximfilter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE i18n SYSTEM "../../include/dtd/i18n.dtd">
<i18n xams-release="0.0.16" file-release="0.1.0" file-revision="1" date="2006-10-21">
    <lngspec name="french" iso="fr" localname="french"/>
    <maintainers>
        <maintainer>
            <name>ACTION-WEB</name>
            <email>xams@actionweb.fr</email>
        </maintainer>
    </maintainers>
    <msgs>
        <title id="Exim-Filter Configuration">Configuration du filtre d'Exim</title>
        <msg id="Exim-Filter Configuration">Configuration du filtre d'Exim</msg>
        <msg id="Filter">Filtre</msg>
        <msg id="Active">Actif</msg>
        <msg id="Filter created">Filtre créé</msg>
        <msg id="Filter last updated">Filtre mis à jour le</msg>

        <!-- Status-Meldungen -->
        <msg id="Filter for User '%s' was added successfully.">Le filtre de l'utilisateur '%s' a été créé avec succès.</msg>
        <msg id="Filter for User '%s' was updated successfully.">Le filtre de l'utilisateur '%s' a été mis à jour avec succès.</msg>
        <msg id="Filter for User '%s' was deleted successfully.">Le filtre de l'utilisateur '%s' a été effacé avec succès.</msg>
        <msg id="Filter for User '%s' could not be added.">Le filtre de l'utilisateur '%s' n'a pas pu être ajouté.</msg>
        <msg id="Filter for User '%s' could not be updated.">Le filtre de l'utilisateur '%s' n'a pas pu être mis à jour.</msg>
        <msg id="Filter for User '%s' could not be deleted.">Le filtre de l'utilisateur '%s' n'a pas pu être effacé.</msg>
    </msgs>
</i18n>

=== stefaweb/XAMS-0.3.x/gui/i18n/french/search.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE i18n SYSTEM "../../include/dtd/i18n.dtd">
<i18n xams-release="0.0.19" file-release="0.1.0" file-revision="1" date="2008-12-03">
    <lngspec name="french" iso="fr" localname="french"/>
    <maintainers>
        <maintainer>
            <name>ACTION-WEB</name>
            <email>xams@actionweb.fr</email>
        </maintainer>
    </maintainers>
    <msgs>
        <title id="Search">Recherche</title>
        <msg id="Search">Recherche</msg>
        <msg id="Site specific">Spécifique au site</msg>
        <msg id="Sitename">Nom du site</msg>
        <msg id="Max. Quota in KB (each User)">Quota maximum en KB (par compte)</msg>
        <msg id="Max. Users">Nbr. maximum de compte</msg>
        <msg id="Max. Aliases">Nbr. maximum d'alias</msg>
        <msg id="Domain specific">Spécifique au domaine</msg>
        <msg id="Domainname">Nom du domaine</msg>
        <msg id="User specific">Spécifique à l'utilisateur</msg>
        <msg id="Account name (E-Mail)">Nom du compte (E-Mail)</msg>
        <msg id="E-Mail Address">Adresse E-Mail</msg>
        <msg id="Alias specific">Spécifique à l'Alias</msg>
        <msg id="Alias Name (Left Part)">Alias (partie gauche)</msg>
        <msg id="Alias Target (Right Part)">Alias (partie droite)</msg>
        <msg id="Note: You can use the %-Sign as wildcard (e.g. Domainname: %foo%)">Commentaire : utilisez le signe % comme caractère de méta-recherche.</msg>
    </msgs>
</i18n>

=== stefaweb/XAMS-0.3.x/gui/i18n/german/db_analyse.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE i18n SYSTEM "../../include/dtd/i18n.dtd">
<i18n xams-release="0.0.9" file-release="0.0.9" file-revision="1" date="2002-11-29">
    <lngspec name="german" iso="de" localname="deutsch"/>
    <maintainers>
        <maintainer>
            <name>XAMS Core-Team</name>
            <email>info@xams.org</email>
        </maintainer>
    </maintainers>    
    <msgs>
        <title id="Database analyse">Datenbank analyse</title>
        <msg id="Database Analyse">Datenbank analyse</msg>
        <msg id="Administrators">Administratoren</msg>
        <msg id="Resellers">Wiederverkäufer</msg>
        <msg id="Customers">Endkunden</msg>
        <msg id="Sites" />
        <msg id="Domains" />
        <msg id="Zones">Zonen</msg>
        <msg id="Users">Benutzer</msg>
        <msg id="Aliases">Aliase</msg>
        <msg id="Log Entries">Log Einträge</msg>
        <msg id="Check database consistency">Datenbankkonsistenz überprüfen</msg>
        <msg id="Checking for Sites without Reseller">Überprüfung von Sites ohne Wiederverkäufer</msg>
        <msg id="Checking for Domains without Sites">Überprüfung von Domains ohne Sites</msg>
        <msg id="Checking for Users without Sites">Überprüfung von Benutzern ohne Sites</msg>
        <msg id="Checking for Aliases without Sites">Überprüfung von Aliasen ohne Sites</msg>
        <msg id="Checking for Users having higher Quota than valid">Überprüfung von Benutzern mit einem höheren Quota als gültig</msg>
        <msg id="Checking for Sites which MaxQuota is not set">Überprüfung von Sites deren maximales Quota nicht gesetzt ist</msg>
        <msg id="Checking for Sites which MaxUsers is not set">Überprüfung von Sites deren maximales Benutzer-Kontingent nicht gesetzt ist</msg>
        <msg id="Checking for Sites which MaxAliases is not set">Überprüfung von Sites deren maximales Alias-Kontingent nicht gesetzt ist</msg>
        <msg id="Checking for Sites containing more aliases than valid">Überprüfung von Sites die mehr Aliase beinhalten als erlaubt</msg>
        <msg id="Checking for Sites containing more users than valid">Überprüfung von Sites die mehr Benutzer beinhalten als erlaubt</msg>
        <msg id="The XAMS-Database is not fully consistent (%s errors)!">Die XAMS-Datenbank ist nicht vollständig konsistent (%s Fehler)</msg>
        <msg id="You should think about limiting MaxQuota/MaxUsers/MaxAliases on Site-Level (%s warnings).">Sie sollten die Limitierung von MaxQuota/MaxUsers/MaxAliases auf Site-Ebene in Erwägung ziehen (%s Warnungen)</msg> 
        <msg id="The XAMS-Database seems to be OK.">Die XAMS-Datenbank scheint in Ordnung zu sein.</msg>
    </msgs>
</i18n>

=== stefaweb/XAMS-0.3.x/gui/i18n/german/site_template.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE i18n SYSTEM "../../include/dtd/i18n.dtd">
<i18n xams-release="0.0.16" file-release="0.0.9" file-revision="1" date="2004-05-18">
    <lngspec name="german" iso="de" localname="deutsch"/>
    <maintainers>
        <maintainer>
            <name>XAMS Core-Team</name>
            <email>info@xams.org</email>
        </maintainer>
    </maintainers>
    <msgs>
        <title id="Site Template Management">Site-Vorlage Verwaltung</title>
        <msg id="Site-Templates Management">Site-Vorlagen Verwaltung</msg>
        <msg id="Template-Name">Name der Vorlage</msg>
        <msg id="Sitename (e.g. xams)">Name der Site (z.B. xams)</msg>
        <msg id="Max. Quota">Max. Kontingent</msg>
        <msg id="Max. Quota (per User)">Max. Kontingent (pro Benutzer)</msg>
        <msg id="Max. Users">Max. Benutzer</msg>
        <msg id="Max. Aliases">Max. Aliase</msg>
        <msg id="Type">Typ</msg>
        <msg id="Viruscheck">Virenprüfung</msg>
        <msg id="Spamcheck">Spamprüfung</msg>
        <msg id="Incoming">Eingehend</msg>
        <msg id="Outgoing">Ausgehend</msg>
        <msg id="Alias" />
        <msg id="is forwarded to">wird weitergeleitet nach</msg>
        <msg id="B&amp;F">B&amp;W</msg>
        <msg id="Template created">Vorlage angelegt</msg>
        <msg id="Template last updated">Vorlage zuletzt aktualisiert</msg>
        <msg id="Viruscheck (Incoming)">Virenprüfung (Eingehend)</msg>
        <msg id="Viruscheck (Outgoing)">Virenprüfung (Ausgehend)</msg>
        <msg id="Spamcheck (Incoming)">Spamprüfung (Eingehend)</msg>
        <msg id="Spamcheck (Outgoing)">Spamprüfung (Ausgehend)</msg>

        <!-- Status-Meldungen -->
        <msg id="Site-Template '%s' was added successfully.">Die Site-Vorlage '%s' wurde erfolgreich hinzugefügt.</msg>
        <msg id="Site-Template '%s' was updated successfully.">Die Site-Vorlage '%s' wurde erfolgreich aktualisiert.</msg>
        <msg id="Site-Template '%s' was deleted successfully.">Die Site-Vorlage '%s' wurde erfolgreich gelöscht.</msg>
        <msg id="Site-Template '%s' could not be added.">Die Site-Vorlage '%s' konnte nicht hinzugefügt werden.</msg>
        <msg id="Site-Template '%s' could not be updated.">Die Site-Vorlage '%s' konnte nicht aktualisiert werden.</msg>
        <msg id="Site-Template '%s' could not be deleted.">Die Site-Vorlage '%s' konnte nicht gelöscht werden.</msg>
    </msgs>
</i18n>

=== stefaweb/XAMS-0.3.x/gui/i18n/french/addressbook.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE i18n SYSTEM "../../include/dtd/i18n.dtd">
<i18n xams-release="0.0.16" file-release="0.1.0" file-revision="1" date="2006-10-21">
    <lngspec name="french" iso="fr" localname="french"/>
    <maintainers>
        <maintainer>
            <name>ACTION-WEB</name>
            <email>xams@actionweb.fr</email>
        </maintainer>
    </maintainers>
    <msgs>
        <title id="Addressbook Management">Administration du Carnet d'Adresse</title>
        <msg id="Site Addressbook Administration">Site - Administration du Carnet d'Adresse</msg>
        <msg id="User Addressbook Administration">Utilisateur - Administration du Carnet d'Adresse</msg>
        <msg id="Alias Addressbook Administration">Alias - Administration du Carnet d'Adresse</msg>
        <msg id="Reseller Addressbook Administration">Revendeur - Administration du Carnet d'Adresse</msg>
        <msg id="Customer Addressbook Administration">Clients - Administration du Carnet d'Adresse</msg>
        <msg id="Fieldname">Nom du champ</msg>
        <msg id="LDAP">LDAP</msg>
        <msg id="ACL Reseller">ACL Revendeur</msg>
        <msg id="ACL Customer">ACL Client</msg>
        <msg id="ACL User">ACL Utilisateur</msg>
        <msg id="Move field">Déplacer le champ</msg>
        <msg id="None">Aucun</msg>
        <msg id="Read">Lecture</msg>
        <msg id="Read+Write">Lecture+Ecriture</msg>
        <msg id="Add new field to Addressbook">Ajouter un nouveau champ au Carnet d'Adresse</msg>
        <msg id="Sites">Sites</msg>
        <msg id="Users">Utilisateurs</msg>
        <msg id="Aliases">Alias</msg>
        <msg id="Resellers">Revendeurs</msg>
        <msg id="Customers">Clients</msg>
        <msg id="No addressbook fields found.">Aucun Carnet d'Adresse trouvé.</msg>
    </msgs>
</i18n>

=== stefaweb/XAMS-0.3.x/gui/i18n/english/std_menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE i18n SYSTEM "../../include/dtd/i18n.dtd">
<i18n xams-release="0.0.16" file-release="0.0.9" file-revision="1" date="2004-05-12">
    <lngspec name="english" iso="en" localname="english"/>
    <maintainers>
        <maintainer>
            <name>XAMS Core-Team</name>
            <email>info@xams.org</email>
        </maintainer>
    </maintainers>    
    <msgs>
        <title id="Standard menu messages" />
        <msg id="Date Format">MM/DD/YYYY</msg>
        <!-- Translating the Date Format means only ordering the letters
        in another way - do not use other letters! -->

        <msg id="Access denied." />
        <msg id="Yes" />
        <msg id="No" />
        <msg id="New" />
        <msg id="Edit" />
        <msg id="Change" />
        <msg id="Update" />
        <msg id="Delete" />
        <msg id="Reset" />
        <msg id="Help" />
        <msg id="Use" />
        <msg id="Limit" />
        <msg id="none" />
        <msg id="unlimited" />
        <msg id="Overview" />
        <msg id="Addressbook" />
        <msg id="Next" />
        <msg id="Add" />
        <msg id="Save" />
        <msg id="On" />
        <msg id="Off" />
        <msg id="The formular was not properly filled out. Point at the question mark." />
        <msg id="Do you really want to delete this entry?" />
        
        <msg id="XAMS Online help" />
        <msg id="Last modification" />
    </msgs>
</i18n>
