=== stefaweb/XAMS-0.3.x/gui/include/dtd/i18n.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT maintainers (maintainer+)>
<!ELEMENT maintainer (name, email)>
<!ELEMENT msgs (title, msg+)>
<!ATTLIST title
    id CDATA #REQUIRED
>
<!ATTLIST msg
    id CDATA #REQUIRED
>
<!ELEMENT title (#PCDATA)>
<!ELEMENT msg (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ATTLIST lngspec
    name CDATA #REQUIRED
    iso CDATA #REQUIRED
    localname CDATA #REQUIRED
>
<!ELEMENT lngspec EMPTY>
<!ELEMENT i18n (lngspec, maintainers, msgs)>
<!ATTLIST i18n
    xams-release CDATA #REQUIRED
    file-release CDATA #REQUIRED
    file-revision CDATA #REQUIRED
    date CDATA #REQUIRED
>

=== stefaweb/XAMS-0.3.x/gui/i18n/german/addressbook.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE i18n SYSTEM "../../include/dtd/i18n.dtd">
<i18n xams-release="0.0.15" file-release="0.0.9" file-revision="1" date="2004-02-12">
    <lngspec name="german" iso="de" localname="deutsch"/>
    <maintainers>
        <maintainer>
            <name>XAMS Core-Team</name>
            <email>info@xams.org</email>
        </maintainer>
    </maintainers>
    <msgs>
        <title id="Addressbook Management">Adressbuch Verwaltung</title>
        <msg id="Site Addressbook Administration">Site-Adressbuch Verwaltung</msg>
        <msg id="User Addressbook Administration">Benutzer-Adressbuch Verwaltung</msg>
        <msg id="Alias Addressbook Administration">Alias-Adressbuch Verwaltung</msg>
        <msg id="Reseller Addressbook Administration">Wiederverkäufer-Adressbuch Verwaltung</msg>
        <msg id="Customer Addressbook Administration">Endkunden-Adressbuch Verwaltung</msg>
        <msg id="Fieldname">Feldname</msg>
        <msg id="LDAP">LDAP</msg>
        <msg id="ACL Reseller">ACL Wiederverkäufer</msg>
        <msg id="ACL Customer">ACL Endkunde</msg>
        <msg id="ACL User">ACL Benutzer</msg>
        <msg id="Move field">Feld verschieben</msg>
        <msg id="None">Nichts</msg>
        <msg id="Read">Lesen</msg>
        <msg id="Read+Write">Lesen+Schreiben</msg>
        <msg id="Add new field to Addressbook">Neues Feld in das Adressbuch hinzufügen</msg>
        <msg id="Sites" />
        <msg id="Users">Benutzer</msg>
        <msg id="Aliases">Aliase</msg>
        <msg id="Resellers">Wiederverkäufer</msg>
        <msg id="Customers">Endkunden</msg>
        <msg id="No addressbook fields found.">Keine Adressbuch-Einträge gefunden.</msg>
    </msgs>
</i18n>

=== stefaweb/XAMS-0.3.x/gui/i18n/english/search.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE i18n SYSTEM "../../include/dtd/i18n.dtd">
<i18n xams-release="0.0.9" file-release="0.0.9" file-revision="1" date="2002-11-29">
    <lngspec name="english" iso="en" localname="english"/>
    <maintainers>
        <maintainer>
            <name>XAMS Core-Team</name>
            <email>info@xams.org</email>
        </maintainer>
    </maintainers>    
    <msgs>
        <title id="Search" />
        <msg id="Search" />
        <msg id="Site specific" />
        <msg id="Sitename" />
        <msg id="Max. Quota in KB (each User)" />
        <msg id="Max. Users" />
        <msg id="Max. Aliases" />
        <msg id="Domain specific" />
        <msg id="Domainname" />
        <msg id="User specific" />
        <msg id="Account name (E-Mail)" />
        <msg id="E-Mail Address" />
        <msg id="Alias specific" />
        <msg id="Alias Name (Left Part)" />
        <msg id="Alias Target (Right Part)" />
        <msg id="Note: You can use the %-Sign as wildcard (e.g. Domainname: %foo%)" />
    </msgs>
</i18n>

=== stefaweb/XAMS-0.3.x/gui/i18n/german/user_template.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE i18n SYSTEM "../../include/dtd/i18n.dtd">
<i18n xams-release="0.0.16" file-release="0.0.9" file-revision="1" date="2004-05-18">
    <lngspec name="german" iso="de" localname="deutsch"/>
    <maintainers>
        <maintainer>
            <name>XAMS Core-Team</name>
            <email>info@xams.org</email>
        </maintainer>
    </maintainers>
    <msgs>
        <title id="User Template Management">Benutzer-Vorlagen Verwaltung</title>
        <msg id="User-Templates Management">Benutzer-Vorlagen Verwaltung</msg>
        <msg id="Template-Name">Name der Vorlage</msg>
        <msg id="Username">Benutzername</msg>
        <msg id="Password">Passwort</msg>
        <msg id="Quota">Kontingent</msg>
        <msg id="Type">Typ</msg>
        <msg id="Viruscheck (Incoming)">Virenprüfung (Eingehend)</msg>
        <msg id="Viruscheck (Outgoing)">Virenprüfung (Ausgehend)</msg>
        <msg id="Spamcheck (Incoming)">Spamprüfung (Eingehend)</msg>
        <msg id="Spamcheck (Outgoing)">Spamprüfung (Ausgehend)</msg>
        <msg id="Spam Score Trigger">Spam Score Trigger</msg>
        <msg id="Spam Score">Spam Score</msg>
        <msg id="High Spam Score">High Spam Score</msg>
        <msg id="Site dependent">Site abhängig</msg>
        <msg id="Relay on auth" />
        <msg id="Relay on check" />
        <msg id="Template created">Vorlage angelegt</msg>
        <msg id="Template last updated">Vorlage zuletzt aktualisiert</msg>

        <!-- Status-Meldungen -->
        <msg id="User-Template '%s' was added successfully.">Die Benutzer-Vorlage '%s' wurde erfolgreich hinzugefügt.</msg>
        <msg id="User-Template '%s' was updated successfully.">Die Benutzer-Vorlage '%s' wurde erfolgreich aktualisiert.</msg>
        <msg id="User-Template '%s' was deleted successfully.">Die Benutzer-Vorlage '%s' wurde erfolgreich gelöscht.</msg>
        <msg id="User-Template '%s' could not be added.">Die Benutzer-Vorlage '%s' konnte nicht hinzugefügt werden.</msg>
        <msg id="User-Template '%s' could not be updated.">Die Benutzer-Vorlage '%s' konnte nicht aktualisiert werden.</msg>
        <msg id="User-Template '%s' could not be deleted.">Die Benutzer-Vorlage '%s' konnte nicht gelöscht werden.</msg>
    </msgs>
</i18n>

=== stefaweb/XAMS-0.3.x/gui/i18n/german/log_entry.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE i18n SYSTEM "../../include/dtd/i18n.dtd">
<i18n xams-release="0.0.9" file-release="0.0.9" file-revision="1" date="2002-11-29">
    <lngspec name="german" iso="de" localname="deutsch"/>
    <maintainers>
        <maintainer>
            <name>XAMS Core-Team</name>
            <email>info@xams.org</email>
        </maintainer>
    </maintainers>    
    <msgs>
        <title id="View Log-Entry">Log-Eintrag einsehen</title>
        <msg id="View Log-Entry">Log-Eintrag einsehen</msg>
    </msgs>
</i18n>

=== stefaweb/XAMS-0.3.x/gui/i18n/english/reseller.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE i18n SYSTEM "../../include/dtd/i18n.dtd">
<i18n xams-release="0.0.16" file-release="0.0.9" file-revision="1" date="2004-05-18">
    <lngspec name="english" iso="en" localname="english"/>
    <maintainers>
        <maintainer>
            <name>XAMS Core-Team</name>
            <email>info@xams.org</email>
        </maintainer>
    </maintainers>
    <msgs>
        <title id="Reseller Management" />
        <msg id="Account Settings" />
        <msg id="Reseller Management" />
        <msg id="Reseller Name" />
        <msg id="Reseller Password" />
        <msg id="Password" />
        <msg id="Max. Customers" />
        <msg id="Max. Sites" />
        <msg id="Max. Domains" />
        <msg id="Max. Users" />
        <msg id="Max. Aliases" />
        <msg id="Max. Quota" />
        <msg id="Max. Site-Quota" />
        <msg id="Max. User-Quota" />
        <msg id="Viruscheck" />
        <msg id="Spamcheck" />
        <msg id="Incoming" />
        <msg id="Outgoing" />
        <msg id="Account locked" />
        <msg id="Sites (multiple selection)" />
        <msg id="No unassigned sites found." />
        <msg id="Reseller created" />
        <msg id="Reseller last updated" />
        <msg id="Spam Score Trigger">Spam Score Trigger</msg>
        <msg id="Spam Score">Spam Score</msg>
        <msg id="High Spam Score">High Spam Score</msg>

        <!-- Status messages -->
        <msg id="Reseller '%s' was added successfully." />
        <msg id="Reseller '%s' was updated successfully." />
        <msg id="Reseller '%s' was deleted successfully." />
        <msg id="Reseller '%s' could not be added." />
        <msg id="Reseller '%s' could not be updated." />
        <msg id="Reseller '%s' could not be deleted." />
    </msgs>
</i18n>

=== stefaweb/XAMS-0.3.x/gui/i18n/german/std_menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE i18n SYSTEM "../../include/dtd/i18n.dtd">
<i18n xams-release="0.0.16" file-release="0.0.9" file-revision="1" date="2004-05-12">
    <lngspec name="german" iso="de" localname="deutsch"/>
    <maintainers>
        <maintainer>
            <name>XAMS Core-Team</name>
            <email>info@xams.org</email>
        </maintainer>
    </maintainers>    
    <msgs>
        <title id="Standard menu messages">Standard Menü-Mitteilungen</title>
        <msg id="Date Format">DD/MM/YYYY</msg>
        <!-- Translating the Date Format means only ordering the letters
        in another way - do not use other letters! -->

        <msg id="Access denied.">Zugriff verweigert.</msg>
        <msg id="Yes">Ja</msg>
        <msg id="No">Nein</msg>
        <msg id="New">Neu</msg>
        <msg id="Edit">Bearbeiten</msg>
        <msg id="Change">Ändern</msg>
        <msg id="Update">Aktualisieren</msg>
        <msg id="Delete">Löschen</msg>
        <msg id="Reset">Zurücksetzen</msg>
        <msg id="Help">Hilfe</msg>
        <msg id="Use">Verwende</msg>
        <msg id="Limit" />
        <msg id="none">keine</msg>
        <msg id="unlimited">unbegrenzt</msg>
        <msg id="Overview">Übersicht</msg>
        <msg id="Addressbook">Adressbuch</msg>
        <msg id="Next">Weiter</msg>
        <msg id="Add">Hinzufügen</msg>
        <msg id="Save">Speichern</msg>
        <msg id="On">Ein</msg>
        <msg id="Off">Aus</msg>
        <msg id="The formular was not properly filled out. Point at the question mark.">Das Formular wurde nicht korrekt ausgefüllt. Zeigen Sie auf die Fragezeichen.</msg>
        <msg id="Do you really want to delete this entry?">Wollen Sie diesen Eintrag wirklich löschen?</msg>
    
        <msg id="XAMS Online help">XAMS Online-Hilfe</msg>
        <msg id="Last modification">Letzte Änderung</msg>
    </msgs>
</i18n>

=== stefaweb/XAMS-0.3.x/gui/i18n/german/user.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE i18n SYSTEM "../../include/dtd/i18n.dtd">
<i18n xams-release="0.0.16" file-release="0.0.9" file-revision="1" date="2004-05-18">
    <lngspec name="german" iso="de" localname="deutsch"/>
    <maintainers>
        <maintainer>
            <name>XAMS Core-Team</name>
            <email>info@xams.org</email>
        </maintainer>
    </maintainers>
    <msgs>
        <title id="User Management">Benutzer Verwaltung</title>
        <msg id="Account Settings">Konto Einstellungen</msg>
        <msg id="User Management">Benutzer Verwaltung</msg>
        <msg id="Site" />
        <msg id="Account name (E-Mail)">Benutzername</msg>
        <msg id="Unique Login name (optional)">Eindeutiger Benutzername</msg>
        <msg id="Password">Passwort</msg>
        <msg id="Quota">Kontingent</msg>
        <msg id="Type">Typ</msg>
        <msg id="Viruscheck (Incoming)">Virenprüfung (Eingehend)</msg>
        <msg id="Viruscheck (Outgoing)">Virenprüfung (Ausgehend)</msg>
        <msg id="Spamcheck (Incoming)">Spamprüfung (Eingehend)</msg>
        <msg id="Spamcheck (Outgoing)">Spamprüfung (Ausgehend)</msg>
        <msg id="Spam Score Trigger">Spam Score Trigger</msg>
        <msg id="Spam Score">Spam Score</msg>
        <msg id="High Spam Score">High Spam Score</msg>
        <msg id="Site dependent">Site abhängig</msg>
        <msg id="Relay on auth" />
        <msg id="Relay on check" />
        <msg id="Auto reply">Automatische Antwort</msg>
        <msg id="Status" />
        <msg id="Filter" />
        <msg id="Active">Aktiv</msg>
        <msg id="Locked">Gesperrt</msg>
        <msg id="Locked &amp; Bounce">Gesperrt &amp; geblockt</msg>
        <msg id="User created">Benutzer angelegt</msg>
        <msg id="User last updated">Benutzer zuletzt aktualisiert</msg>
        <msg id="This unique username does already exists">Dieser Eindeutige Benutzername existiert bereits</msg>
        <msg id="Subject">Betreff</msg>
        <msg id="Message">Nachricht</msg>
        <msg id="Unfortunately no more users can be added. Reseller's User-Quota has reached.">Leider können keine weiteren Benutzer hinzugefügt werden. Das Benutzerkontingent des Wiederverkäufers ist erschöpft.</msg>
        <msg id="Unfortunately no more users can be added. The site based User-Quota has reached.">Leider können keine weiteren Benutzer hinzugefügt werden. Das Site-basierte Benutzerkontingent ist erschöpft.</msg>
        <msg id="Unfortunately no more users can be added. The site based Quota has reached.">Leider können keine weiteren Benutzer hinzugefügt werden. Das Site-basierte Postfachgrößenkontingent ist erschöpft.</msg>
        <msg id="Unknown error occured.">Ein unbekannter Fehler ist aufgetreten.</msg>
        <msg id="Contain non-numeric Characters">enthält nicht-numerische Zeichen</msg>
        <msg id="Field has to be filled out">Feld muss ausgefüllt werden</msg>
        <msg id="Invalid ID">Ungültige ID</msg>
        <msg id="Select a Site in the drop-down menu.">Wählen Sie eine Site aus dem Drop-Down Menü</msg>
        <msg id="Site does not allow users having incoming viruscheck.">Site verbietet Benutzern eingehenden Virus-Check,</msg>
        <msg id="Site does not allow users having outgoing viruscheck.">Site verbietet Benutzern ausgehenden Virus-Check,</msg>
        <msg id="Site does not allow users having incoming spamcheck.">Site verbietet Benutzern eingehenden Spam-Check,</msg>
        <msg id="Site does not allow users having outgoing spamcheck.">Site verbietet Benutzern ausgehenden Spam-Check.</msg>
        <msg id="Selected AddrType is not allowed.">Gewählter Adress-Typ ist nicht erlaubt.</msg>

        <!-- Errors function -->
        <msg id="Too short (min='%s')">Zu kurz (minimum='%s')</msg>
        <msg id="Too long (max='%s')">Zu lang (maximum='%s')</msg>
        <msg id="Value is too low (min='%s')">Wert ist zu niedrig (minimum='%s')</msg>
        <msg id="Value is too big (max='%s')">Wert ist zu hoch (maximum='%s')</msg>
        
        <!-- Status-Meldungen -->
        <msg id="User '%s' was added successfully.">Der Benutzer '%s' wurde erfolgreich hinzugefügt.</msg>
        <msg id="User '%s' was updated successfully.">Der Benutzer '%s' wurde erfolgreich aktualisiert.</msg>
        <msg id="User '%s' was deleted successfully.">Der Benutzer '%s' wurde erfolgreich gelöscht.</msg>
        <msg id="User '%s' could not be added.">Der Benutzer '%s' konnte nicht hinzugefügt werden.</msg>
        <msg id="User '%s' could not be updated.">Der Benutzer '%s' konnte nicht aktualisiert werden.</msg>
        <msg id="User '%s' could not be deleted.">Der Benutzer '%s' konnte nicht gelöscht werden.</msg>
    </msgs>
</i18n>

=== stefaweb/XAMS-0.3.x/gui/i18n/english/alias.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE i18n SYSTEM "../../include/dtd/i18n.dtd">
<i18n xams-release="0.0.19" file-release="0.0.9" file-revision="1" date="2009-02-17">
    <lngspec name="english" iso="en" localname="english"/>
    <maintainers>
        <maintainer>
            <name>XAMS Core-Team</name>
            <email>info@xams.org</email>
        </maintainer>
    </maintainers>    
    <msgs>
        <title id="Alias Management" />
        <msg id="Alias Management" />
        <msg id="Unfortunately no more aliases can be added. Site based Alias-Quota has reached." />
        <msg id="Unfortunately no more aliases can be added. Reseller based Alias-Quota has reached." />
        <msg id="Unfortunately no more aliases can be added. Your Alias-Quota has reached." />
        <msg id="Site" />
        <msg id="Incoming Address" />
        <msg id="Forward Address" />
        <msg id="Bounce and Forward" />
        <msg id="Blackhole" />
        <msg id="Alias created" />
        <msg id="Alias last updated" />
	<msg id="Select a Site in the drop-down menu." />

        <!-- Status messages -->
        <msg id="Alias '%s' was added successfully." />
        <msg id="Alias '%s' was updated successfully." />
        <msg id="Alias '%s' was deleted successfully." />
        <msg id="Alias '%s' could not be added." />
        <msg id="Alias '%s' could not be updated." />
        <msg id="Alias '%s' could not be deleted." />
    </msgs>
</i18n>
