=== stefaweb/XAMS-0.3.x/gui/include/dtd/i18n.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT maintainers (maintainer+)>
<!ELEMENT maintainer (name, email)>
<!ELEMENT msgs (title, msg+)>
<!ATTLIST title
    id CDATA #REQUIRED
>
<!ATTLIST msg
    id CDATA #REQUIRED
>
<!ELEMENT title (#PCDATA)>
<!ELEMENT msg (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ATTLIST lngspec
    name CDATA #REQUIRED
    iso CDATA #REQUIRED
    localname CDATA #REQUIRED
>
<!ELEMENT lngspec EMPTY>
<!ELEMENT i18n (lngspec, maintainers, msgs)>
<!ATTLIST i18n
    xams-release CDATA #REQUIRED
    file-release CDATA #REQUIRED
    file-revision CDATA #REQUIRED
    date CDATA #REQUIRED
>

=== stefaweb/XAMS-0.3.x/gui/i18n/english/site.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE i18n SYSTEM "../../include/dtd/i18n.dtd">
<i18n xams-release="0.0.16" file-release="0.0.9" file-revision="1" date="2004-05-18">
    <lngspec name="english" iso="en" localname="english"/>
    <maintainers>
        <maintainer>
            <name>XAMS Core-Team</name>
            <email>info@xams.org</email>
        </maintainer>
    </maintainers>
    <msgs>
        <title id="Site Management" />
        <msg id="Site Management" />
        <msg id="Unfortunately no more sites can be added. Your Site-Quota has reached." />
	<msg id="Unfortunately no more domains can be added. Reseller's Domain-Quota has reached." />
        <msg id="Reseller" />
        <msg id="Sitename" />
        <msg id="Domains" />
        <msg id="Max. Quota" />
        <msg id="Max. User-Quota" />
        <msg id="Max. Users" />
        <msg id="Max. Aliases" />
        <msg id="Type" />
        <msg id="Viruscheck" />
        <msg id="Spamcheck" />
        <msg id="Incoming" />
        <msg id="Outgoing" />
        <msg id="Status" />
        <msg id="Active" />
        <msg id="Locked" />
        <msg id="Locked &amp; Bounce" />
        <msg id="Site created" />
        <msg id="This Site does already exists" />
	<msg id="Forbidden characters in Site name" />
        <msg id="Site last updated" />
        <msg id="New User" />
        <msg id="Spam Score Trigger">Spam Score Trigger</msg>
        <msg id="Spam Score">Spam Score</msg>
        <msg id="High Spam Score">High Spam Score</msg>
	<msg id="Select a Reseller in the drop-down menu" />
	<msg id="Invalid ID" />

        <!-- Status messages -->
        <msg id="Site '%s' was added successfully." />
        <msg id="Site '%s' was updated successfully." />
        <msg id="Site '%s' was deleted successfully." />
        <msg id="Site '%s' could not be added." />
        <msg id="Site '%s' could not be updated." />
        <msg id="Site '%s' could not be deleted." />
    </msgs>
</i18n>

=== stefaweb/XAMS-0.3.x/gui/i18n/english/customer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE i18n SYSTEM "../../include/dtd/i18n.dtd">
<i18n xams-release="0.0.9" file-release="0.0.9" file-revision="1" date="2002-11-29">
    <lngspec name="english" iso="en" localname="english"/>
    <maintainers>
        <maintainer>
            <name>XAMS Core-Team</name>
            <email>info@xams.org</email>
        </maintainer>
    </maintainers>    
    <msgs>
        <title id="Customer Management" />
        <msg id="Account Settings" />
        <msg id="Customer Management" />
        <msg id="Customer Name" />
        <msg id="Customer Password" />
        <msg id="Password" />
        <msg id="Account locked" />
        <msg id="Reseller" />
        <msg id="Sites" />
        <msg id="Customer created" />
        <msg id="Customer last updated" />
        <msg id="Unfortunately no more customers can be added. Your Customer-Limit has reached." />
        <msg id="Unfortunately no more customers can be added. The Customer-Limit of the selected Reseller has reached." />

        <!-- Status messages -->
        <msg id="Customer '%s' was added successfully." />
        <msg id="Customer '%s' was updated successfully." />
        <msg id="Customer '%s' was deleted successfully." />
        <msg id="Customer '%s' could not be added." />
        <msg id="Customer '%s' could not be updated." />
        <msg id="Customer '%s' could not be deleted." />
    </msgs>
</i18n>

=== stefaweb/XAMS-0.3.x/gui/i18n/english/eximfilter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE i18n SYSTEM "../../include/dtd/i18n.dtd">
<i18n xams-release="0.0.9" file-release="0.0.9" file-revision="1" date="2002-11-29">
    <lngspec name="english" iso="en" localname="english"/>
    <maintainers>
        <maintainer>
            <name>XAMS Core-Team</name>
            <email>info@xams.org</email>
        </maintainer>
    </maintainers>    
    <msgs>
        <title id="Exim-Filter Configuration" />
        <msg id="Exim Filter Configuration" />
        <msg id="Filter" />
        <msg id="Active" />
        <msg id="Filter created" />
        <msg id="Filter last updated" />

        <!-- Status messages -->
        <msg id="Filter for User '%s' was added successfully." />
        <msg id="Filter for User '%s' was updated successfully." />
        <msg id="Filter for User '%s' was deleted successfully." />
        <msg id="Filter for User '%s' could not be added." />
        <msg id="Filter for User '%s' could not be updated." />
        <msg id="Filter for User '%s' could not be deleted." />
    </msgs>
</i18n>

=== stefaweb/XAMS-0.3.x/gui/i18n/german/startup.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE i18n SYSTEM "../../include/dtd/i18n.dtd">
<i18n xams-release="0.0.19" file-release="0.0.1" file-revision="1" date="2009-04-02">
    <lngspec name="english" iso="en" localname="english"/>
    <maintainers>
        <maintainer>
            <name>XAMS Core-Team</name>
            <email>info@xams.org</email>
        </maintainer>
    </maintainers>
    <msgs>
        <title id="System Overview">System Übersicht</title>
        <msg id="System Overview">System Übersicht</msg>
        <msg id="Reseller">Wiederverkäufer</msg>
        <msg id="Site">Site</msg>
        <msg id="Add User">Benutzer hinzufügen</msg>
        <msg id="Add Alias">Alias hinzufügen</msg>
        <msg id="Actions">Aktionen</msg>
        <msg id="Show all Sites">Alle Sites anzeigen</msg>
    </msgs>
</i18n>

=== stefaweb/XAMS-0.3.x/gui/i18n/german/eximfilter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE i18n SYSTEM "../../include/dtd/i18n.dtd">
<i18n xams-release="0.0.9" file-release="0.0.9" file-revision="1" date="2002-11-29">
    <lngspec name="german" iso="de" localname="deutsch"/>
    <maintainers>
        <maintainer>
            <name>XAMS Core-Team</name>
            <email>info@xams.org</email>
        </maintainer>
    </maintainers>    
    <msgs>
        <title id="Exim-Filter Configuration">Exim-Filter Konfiguration</title>
        <msg id="Exim-Filter Configuration">Exim-Filter Konfiguration</msg>
        <msg id="Filter" />
        <msg id="Active">Aktiv</msg>
        <msg id="Filter created">Filter angelegt</msg>
        <msg id="Filter last updated">Filter zuletzt aktualisiert</msg>

        <!-- Status-Meldungen -->
        <msg id="Filter for User '%s' was added successfully.">Der Filter für den Benutzer '%s' wurde erfolgreich hinzugefügt.</msg>
        <msg id="Filter for User '%s' was updated successfully.">Der Filter für den Benutzer '%s' wurde erfolgreich aktualisiert.</msg>
        <msg id="Filter for User '%s' was deleted successfully.">Der Filter für den Benutzer '%s' wurde erfolgreich gelöscht.</msg>
        <msg id="Filter for User '%s' could not be added.">Der Filter für den Benutzer '%s' konnte nicht hinzugefügt werden.</msg>
        <msg id="Filter for User '%s' could not be updated.">Der Filter für den Benutzer '%s' konnte nicht aktualisiert werden.</msg>
        <msg id="Filter for User '%s' could not be deleted.">Der Filter für den Benutzer '%s' konnte nicht gelöscht werden.</msg>
    </msgs>
</i18n>

=== stefaweb/XAMS-0.3.x/gui/i18n/english/site_template.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE i18n SYSTEM "../../include/dtd/i18n.dtd">
<i18n xams-release="0.0.16" file-release="0.0.9" file-revision="1" date="2004-05-18">
    <lngspec name="english" iso="en" localname="english"/>
    <maintainers>
        <maintainer>
            <name>XAMS Core-Team</name>
            <email>info@xams.org</email>
        </maintainer>
    </maintainers>
    <msgs>
        <title id="Site Template Management" />
        <msg id="Site-Templates Management" />
        <msg id="Template-Name" />
        <msg id="Sitename (e.g. xams)" />
        <msg id="Max. Quota" />
        <msg id="Max. Quota (per User)" />
        <msg id="Max. Users" />
        <msg id="Max. Aliases" />
        <msg id="Type" />
        <msg id="Viruscheck" />
        <msg id="Spamcheck" />
        <msg id="Incoming" />
        <msg id="Outgoing" />
        <msg id="Alias" />
        <msg id="is forwarded to" />
        <msg id="B&amp;F" />
        <msg id="Template created" />
        <msg id="Template last updated" />
        <msg id="Spam Score Trigger">Spam Score Trigger</msg>
        <msg id="Spam Score">Spam Score</msg>
        <msg id="High Spam Score">High Spam Score</msg>
        <msg id="Viruscheck (Incoming)" />
        <msg id="Viruscheck (Outgoing)" />
        <msg id="Spamcheck (Incoming)" />
        <msg id="Spamcheck (Outgoing)" />

        <!-- Status messages -->
        <msg id="Site-Template '%s' was added successfully." />
        <msg id="Site-Template '%s' was updated successfully." />
        <msg id="Site-Template '%s' was deleted successfully." />
        <msg id="Site-Template '%s' could not be added." />
        <msg id="Site-Template '%s' could not be updated." />
        <msg id="Site-Template '%s' could not be deleted." />
    </msgs>
</i18n>

=== stefaweb/XAMS-0.3.x/gui/i18n/french/startup.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE i18n SYSTEM "../../include/dtd/i18n.dtd">
<i18n xams-release="0.0.19" file-release="0.0.1" file-revision="1" date="2009-03-18">
    <lngspec name="english" iso="en" localname="english"/>
    <maintainers>
        <maintainer>
            <name>XAMS Core-Team</name>
            <email>info@xams.org</email>
        </maintainer>
    </maintainers>
    <msgs>
        <title id="System Overview">Vue Génèrale</title>
        <msg id="System Overview">Vue génèrale</msg>
	<msg id="Reseller">Revendeur</msg>
        <msg id="Site">Site</msg>
        <msg id="Add User">Ajouter un utilisateur</msg>
        <msg id="Add Alias">Ajouter un Alias</msg>
        <msg id="Actions">Actions</msg>
        <msg id="Show all Sites">Montrer tous les Sites</msg>
    </msgs>
</i18n>

=== stefaweb/XAMS-0.3.x/gui/i18n/english/user_template.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE i18n SYSTEM "../../include/dtd/i18n.dtd">
<i18n xams-release="0.0.16" file-release="0.0.9" file-revision="1" date="2004-05-18">
    <lngspec name="english" iso="en" localname="english"/>
    <maintainers>
        <maintainer>
            <name>XAMS Core-Team</name>
            <email>info@xams.org</email>
        </maintainer>
    </maintainers>
    <msgs>
        <title id="User Template Management" />
        <msg id="User-Templates Management" />
        <msg id="Template-Name" />
        <msg id="Username" />
        <msg id="Password" />
        <msg id="Quota" />
        <msg id="Type" />
        <msg id="Viruscheck (Incoming)" />
        <msg id="Viruscheck (Outgoing)" />
        <msg id="Spamcheck (Incoming)" />
        <msg id="Spamcheck (Outgoing)" />
	<msg id="Spam Score Trigger" />
	<msg id="Spam Score" />
	<msg id="High Spam Score" />
        <msg id="Site dependent" />
        <msg id="Relay on auth" />
        <msg id="Relay on check" />
        <msg id="Template created" />
        <msg id="Template last updated" />

        <!-- Status messages -->
        <msg id="User-Template '%s' was added successfully." />
        <msg id="User-Template '%s' was updated successfully." />
        <msg id="User-Template '%s' was deleted successfully." />
        <msg id="User-Template '%s' could not be added." />
        <msg id="User-Template '%s' could not be updated." />
        <msg id="User-Template '%s' could not be deleted." />
    </msgs>
</i18n>
